import globals.Globals

CSTR = recipemap('continuous_stirred_tank_reactor')
DRYER = recipemap('dryer')
CRYSTALLIZER = recipemap('crystallizer')
SOLIDIFIER = recipemap('fluid_solidifier')
TBR = recipemap('trickle_bed_reactor')
DISTILLERY = recipemap('distillery')
BR = recipemap('batch_reactor')
FORMING_PRESS = recipemap('forming_press')

//Paracetemol

CSTR.recipeBuilder()
    .fluidInputs(fluid('diluted_nitric_acid') * 50)
    .fluidInputs(fluid('phenol') * 50)
    .fluidOutputs(fluid('ortho_para_nitrophenol_solution') * 100)
    .duration(5)
    .EUt(Globals.voltAmps[3])
    .buildAndRegister()

DRYER.recipeBuilder()
    .fluidInputs(fluid('ortho_para_nitrophenol_solution') * 2000)
    .fluidInputs(fluid('hot_air') * 8000)
    .outputs(metaitem('dustOrthoParaNitrophenolMixture') * 1)
    .duration(100)
    .EUt(Globals.voltAmps[3])
    .buildAndRegister()

CRYSTALLIZER.recipeBuilder()
    .fluidInputs(fluid('ortho_para_nitrophenol_mixture') * 144)
    .outputs(metaitem('dustSusyFourNitrophenol') * 15)
    .fluidOutputs(fluid('susy_two_nitrophenol') * 2160)
    .duration(100)
    .EUt(Globals.voltAmps[3])
    .buildAndRegister()

FLUID_SOLIDIFIER.recipeBuilder()
    .fluidInputs(fluid('susy_two_nitrophenol') * 144)
    .outputs(metaitem('dustSusyTwoNitrophenol') * 1)
    .duration(100)
    .EUt(Globals.voltAmps[3])
    .buildAndRegister()

TBR.recipeBuilder()
    .inputs(ore('dustSusyFourNitrophenol') * 15)
    .fluidInputs(fluid('hydrogen') * 6000)
    .notConsumable(metaitem('dustActivatedRaneyNickel'))
    .fluidOutputs(fluid('four_aminophenol_solution') * 2000)
    .duration(100)
    .EUt(Globals.voltAmps[3])
    .buildAndRegister()

DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('four_aminophenol_solution') * 2000)
    .outputs(metaitem('dustSusyFourAminophenol') * 15)
    .fluidOutputs(fluid('water') * 2000)
    .duration(100)
    .EUt(Globals.voltAmps[3])
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustSusyFourAminophenol') * 15)
    .fluidInputs(fluid('gtfo_acetic_anhydride') * 1000)
    .outputs(metaitem('dustParacetamol') * 20)
    .fluidOutputs(fluid('acetic_acid') * 2000)
    .duration(100)
    .EUt(Globals.voltAmps[3])
    .buildAndRegister()

// Paracetamol Caplet * 1
mods.gregtech.forming_press.removeByInput(30, [metaitem('gregtechfoodoption:component.caplet_body'), metaitem('dustSmallParacetamol'), metaitem('gregtechfoodoption:component.caplet_cap'), metaitem('circuit.integrated').withNbt(['Configuration': 3])], null)

FORMING_PRESS.recipeBuilder() 
    .inputs(metaitem('gregtechfoodoption:component.caplet_body') * 8)
    .inputs(ore('dustParacetamol') * 1)
    .inputs(metaitem('gregtechfoodoption:component.caplet_cap') * 8)
    .outputs(metaitem('gregtechfoodoption:food.paracetamol_caplet') * 8)
    .duration(100)
    .EUt(Globals.voltAmps[5])
    .buildAndRegister() 
