name = "Supersymmetry"
author = "SymmetricDevs"
version = "0.1.15.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4bf8a47654d8350e843d02bb3ce06b1354aed33e7db78b771c52dde2e6c9273"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
