name = "Supersymmetry"
author = "SymmetricDevs"
version = "0.1.14.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c20ef8a817ad07b78eb3357fed1ef27496399497658362bef1f64abe1600e1a8"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
