name = "Supersymmetry"
author = "SymmetricDevs"
version = "0.1.14.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df67b6748dea5a78070620be7655fddf07b160b96513e6d171c220fd58f13340"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
