name = "Supersymmetry"
author = "SymmetricDevs"
version = "0.1.14.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf5cdd94ef49fa845e9bad6c2c22e16176af1398b1f36e1d99dfc037420772bc"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
