name = "Supersymmetry"
author = "SymmetricDevs"
version = "0.1.14.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2619797b5997400e39c17b4e1d1051f07855cfe0507b19d92e40e67d5abbce00"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
