name = "Supersymmetry"
author = "SymmetricDevs"
version = "0.1.14.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7bd8cb91f935ac7735dd59549325e6eac500941630fd77acaaefe428bab00d3"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
