name = "Supersymmetry"
author = "SymmetricDevs"
version = "0.1.14.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "949e43f34c644a5312ff3ce61175ccb7b21aae751610bb14699ba1a7d5c9646e"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
