name = "Supersymmetry"
author = "SymmetricDevs"
version = "0.1.14.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cdefcd78b0bb1151913615fa9d2eb5dfdc7e253124eecbff5b3fae24000319f"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
