name = "Supersymmetry"
author = "SymmetricDevs"
version = "0.1.14.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30c11423d6e2799ad11d942fdb741c531d97c42a986424a93e83da6540eb97d8"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
