name = "Supersymmetry"
author = "SymmetricDevs"
version = "0.1.14.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c561c555771a7b4ddba57674ae20260baf05261f4e36b4917093966224a6f20d"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
