import globals.Globals
import static globals.SinteringGlobals.*

GRAVITY_SEPARATOR = recipemap('gravity_separator')
MIXER = recipemap('mixer')
FROTH_FLOTATION = recipemap('froth_flotation')
CLARIFIER = recipemap('clarifier')
ROASTER = recipemap('roaster')
ROTARY_KILN = recipemap('rotary_kiln')
BR = recipemap('batch_reactor')
BLENDER = recipemap('blender')
FLUIDIZED_BED_REACTOR = recipemap('fluidized_bed_reactor')
ION_EXCHANGE = recipemap('ion_exchange_column')
CENTRIFUGE = recipemap('centrifuge')
LCR = recipemap('large_chemical_reactor')
ELECTROLYTIC_CELL = recipemap('electrolytic_cell')
SIFTER = recipemap('sifter')
VACUUM_CHAMBER = recipemap('vacuum_chamber')
CRYSTALLIZER = recipemap('crystallizer')
MACERATOR = recipemap('macerator')

MACERATOR.recipeBuilder()
    .inputs(item('susy:resource_block', 7))
    .outputs(metaitem('dustBastnasite') * 4)
    .duration(240)
    .EUt(7)
    .buildAndRegister()

// Bastnasite beneficiation

GRAVITY_SEPARATOR.recipeBuilder()
    .inputs(ore('dustBastnasite'))
    .outputs(metaitem('dustSiftedBastnasite'))
    .chancedOutput(metaitem('dustLimestoneTailings'), 3000, 0)
    .chancedOutput(metaitem('dustBarite'), 500, 0)
    .chancedOutput(metaitem('dustStrontianite'), 100, 0)
    .duration(40)
    .EUt(30)
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(ore('dustSiftedBastnasite') * 8)
    .fluidInputs(fluid('distilled_water') * 2000)
    .fluidOutputs(fluid('impure_bastnasite_slurry') * 2000)
    .duration(80)
    .EUt(480)
    .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
    .notConsumable(fluid('methyl_isobutyl_carbinol') * 100)
    .notConsumable(fluid('oleic_acid') * 1000)
    .notConsumable(inputs('dustSodaAsh') * 5)
    .fluidInputs(fluid('impure_bastnasite_slurry') * 2000)
    .fluidOutputs(fluid('bastnasite_slurry') * 1000)
    .fluidOutputs(fluid('pegmatite_tailing_slurry') * 1000)
    .duration(80)
    .EUt(480)
    .buildAndRegister()

CLARIFIER.recipeBuilder()
    .fluidInputs(fluid('bastnasite_slurry') * 1000)
    .outputs(metaitem('dustFlotatedBastnasite') * 8)
    .fluidOutputs(fluid('wastewater') * 1000)
    .duration(20)
    .EUt(30)
    .buildAndRegister()

for (fuel in sintering_fuels) {
    if (!fuel.isPlasma) {
        ROTARY_KILN.recipeBuilder()
                .inputs(ore('dustFlotatedBastnasite') * 2)
                .fluidInputs(fluid('sulfuric_acid') * 4000)
                .outputs(metaitem('dustRoastedBastnasite') * 2)
                .fluidOutputs(fluid('hydrogen_fluoride') * 2000)
                .fluidOutputs(fluid('carbon_dioxide') * 2000)
                .fluidOutputs(fluid('dense_steam') * 2000)
                .duration(80)
                .EUt(120)
                .buildAndRegister()
    }
}   

BR.recipeBuilder()
    .inputs(ore('dustRoastedBastnasite') * 2)
    .fluidInputs(fluid('salt_water') * 2000)
    .outputs(metaitem('dustConcentratedBastnasite') * 2) // REENa(SO4)2 x2
    .fluidOutputs(fluid('wastewater') * 2000)
    .duration(40)
    .EUt(120)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustConcentratedBastnasite'))
    .inputs(ore('dustSodiumHydroxide') * 9)
    .fluidInputs(fluid('distilled_water') * 2000)
    .outputs(metaitem('dustBastReHydroxides'))
    .fluidOutputs(fluid('sodium_sulfate_solution') * 2000)
    .duration(40)
    .EUt(30)
    .buildAndRegister()

// Bastnasite Concentrate Processing

MIXER.recipeBuilder()
    .inputs(ore('dustBastReHydroxides'))
    .inputs(ore('dustPotassiumPermanganate') * 3)
    .fluidInputs(fluid('nitric_acid') * 5000)
    .fluidOutputs(fluid('bast_ox_re_nitrates_solution') * 1000)
    .duration(80)
    .EUt(120)
    .buildAndRegister()

BLENDER.recipeBuilder()
    .fluidInputs(fluid('bast_ox_re_nitrates_solution') * 1000)
    .fluidInputs(fluid('tributyl_phosphate') * 1000)
    .fluidOutputs(fluid('bast_cerium_extract') * 1000)
    .fluidOutputs(fluid('bast_cefree_re_nitrates_solution') * 1000)
    .duration(80)
    .EUt(120)
    .buildAndRegister()

BLENDER.recipeBuilder()
    .fluidInputs(fluid('bast_cefree_re_nitrates_solution') * 1000)
    .fluidInputs(fluid('rare_earth_extraction_mixture') * 100)
    .fluidOutputs(fluid('bast_lree_concentrate') * 250)
    .fluidOutputs(fluid('bast_dehpa_extract') * 1000)
    .duration(80)
    .EUt(120)
    .buildAndRegister()

MIXER.recipeBuilder()
    .fluidInputs(fluid('hydrochloric_acid') * 50)
    .fluidInputs(fluid('bast_dehpa_extract') * 1000)
    .fluidOutputs(fluid('rare_earth_extraction_mixture') * 100)
    .fluidOutputs(fluid('bast_re_chlorides_solution') * 1000)
    .duration(80)
    .EUt(120)
    .buildAndRegister()

BLENDER.recipeBuilder()
    .fluidInputs(fluid('bast_re_chlorides_solution') * 1000)
    .fluidInputs(fluid('rare_earth_separation_mixture') * 100)
    .fluidOutputs(fluid('bast_mree_concentrate') * 125)
    .fluidOutputs(fluid('bast_ehehpa_extract') * 1000)
    .duration(80)
    .EUt(120)
    .buildAndRegister()

MIXER.recipeBuilder()
    .fluidInputs(fluid('hydrochloric_acid') * 50)
    .fluidInputs(fluid('bast_ehehpa_extract') * 1000)
    .fluidOutputs(fluid('rare_earth_separation_mixture') * 100)
    .fluidOutputs(fluid('bast_hree_concentrate') * 20)
    .duration(80)
    .EUt(120)
    .buildAndRegister()

// Bastnasite Element Extraction

MIXER.recipeBuilder()
    .fluidInputs(fluid('bast_cerium_extract') * 1000)
    .fluidInputs(fluid('diluted_hydrochloric_acid') * 10)
    .chancedOutput(metaitem('dustCeriumIvNitrate') * 17, 5200, 0)
    .fluidOutputs(fluid('tributyl_phosphate') * 1000)
    .duration(120)
    .EUt(30)
    .buildAndRegister()

FLUIDIZED_BED_REACTOR.recipeBuilder()
    .inputs(ore('dustAmmoniumCarbonate') * 42)
    .fluidInputs(fluid('bast_lree_concentrate') * 1000)
    .chancedOutput(metaitem('dustLanthanumCarbonate') * 14, 5200, 0)
    .fluidOutputs(fluid('bast_lafree_lree_concentrate') * 1000)
    .duration(40)
    .EUt(120)
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(ore('dustSodiumHydroxide') * 30)
    .fluidInputs(fluid('bast_lafree_lree_concentrate') * 1000)
    .fluidOutputs(fluid('bast_lafree_lree_hydroxides') * 1000)
    .duration(80)
    .EUt(30)
    .buildAndRegister()

MIXER.recipeBuilder()
    .notConsumable(fluid('sodium_hydroxide') * 432)
    .inputs(ore('dustSodiumChlorate') * 5)
    .fluidInputs(fluid('bast_lafree_lree_hydroxides') * 1000)
    .fluidOutputs(fluid('bast_oxidised_lree_hydroxides') * 1000)
    .duration(80)
    .EUt(30)
    .buildAndRegister()

CENTRIFUGE.recipeBuilder()
    .fluidInputs(fluid('bast_oxidised_lree_hydroxides') * 1000)
    .chancedOutput(metaitem('dustPraseodymiumOxide') * 3, 9600, 0)
    .fluidOutputs(fluid('bast_prfree_lree_hydroxides') * 1000)
    .duration(120)
    .EUt(120)
    .buildAndRegister()

MIXER.recipeBuilder()
    .fluidInputs(fluid('distilled_water') * 1000)
    .fluidInputs(fluid('bast_prfree_lree_hydroxides') * 1000)
    .chancedOutput(metaitem('dustNeodymiumHydroxide') * 14, 9600, 0)
    .fluidOutputs(fluid('bast_lree_waste') * 1000)
    .duration(80)
    .EUt(16)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustSmallZinc') * 6)
    .fluidInputs(fluid('bast_mree_concentrate') * 1000)
    .fluidInputs(fluid('sulfuric_acid') * 1000)
    .chancedOutput(metaitem('dustEuropiumIiSulfate') * 6, 7200, 0)
    .fluidOutputs(fluid('bast_eufree_mree_concentrate') * 1000)
    .duration(100)
    .EUt(120)
    .buildAndRegister()

LCR.recipeBuilder()
    .fluidInputs(fluid('bast_eufree_mree_concentrate') * 1000)
    .fluidInputs(fluid('sodium_amalgam') * 800)
    .fluidOutputs(fluid('samarium_amalgam') * 800)
    .fluidOutputs(fluid('bast_smfree_mree_concentrate') * 1000)
    .duration(80)
    .EUt(480)
    .buildAndRegister()

ION_EXCHANGE.recipeBuilder()
    .inputs(metaitem('beads.strong_basic_anion_exchange') * 7)
    .fluidInputs(fluid('bast_smfree_mree_concentrate') * 1000)
    .outputs(metaitem('beads.loaded_gadolinium_anion_exchange') * 7)
    .fluidOutputs(fluid('bast_gdfree_mree_concentrate') * 1000)
    .duration(400)
    .EUt(16)
    .buildAndRegister()

ELECTROLYTIC_CELL.recipeBuilder()
    .inputs(ore('dustPotassiumCarbonate') * 18)
    .notConsumable(metaitem('stickPlatinum'))
    .notConsumable(fluid('potassium_hydroxide_solution') * 432)
    .fluidInputs(fluid('bast_gdfree_mree_concentrate') * 1000)
    .chancedOutput(metaitem('dustTerbiumCarbonate') * 14, 3040, 0)
    .fluidOutputs(fluid('bast_tbfree_mree_concentrate') * 1000)
    .duration(100)
    .EUt(1920)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustSodiumFluoride') * 6)
    .fluidInputs(fluid('bast_tbfree_mree_concentrate') * 1000)
    .chancedOutput(metaitem('dustDysprosiumFluoride') * 4, 6080, 0)
    .fluidOutputs(fluid('bast_mree_waste') * 1000)
    .duration(80)
    .EUt(120)
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('bast_hree_concentrate') * 1000)
    .fluidInputs(fluid('sodium_chromate_solution') * 2000)
    .outputs(metaitem('dustBastHreeDoubleChromates'))
    .fluidOutputs(fluid('yttrium_chloride_solution') * 800)
    .duration(60)
    .EUt(60)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustBastHreeDoubleChromates'))
    .fluidInputs(fluid('hydrochloric_acid') * 4000)
    .fluidOutputs(fluid('bast_yfree_hree_concentrate') * 1000)
    .fluidOutputs(fluid('hydrogen') * 2000)
    .duration(60)
    .EUt(60)
    .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
    .notConsumable(fluid('two_ethylhexanol') * 1000)
    .fluidInputs(fluid('bast_yfree_hree_concentrate') * 1000)
    .fluidInputs(fluid('sodium_hydroxide_solution') * 100)
    .fluidInputs(fluid('sodium_dodecyl_sulfate_solution') * 3000)
    .chancedOutput(metaitem('dustErbiumDodecylSulfate'), 5000, 0)
    .fluidOutputs(fluid('bast_erfree_hree_concentrate') * 1000)
    .duration(120)
    .EUt(120)
    .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
    .notConsumable(fluid('two_ethylhexanol') * 1000)
    .fluidInputs(fluid('bast_erfree_hree_concentrate') * 3000)
    .fluidInputs(fluid('sodium_hydroxide_solution') * 100)
    .fluidInputs(fluid('sodium_dodecyl_sulfate_solution') * 3000)
    .chancedOutput(metaitem('dustHolmiumDodecylSulfate'), 5000, 0)
    .fluidOutputs(fluid('bast_hofree_hree_concentrate') * 1000)
    .duration(120)
    .EUt(120)
    .buildAndRegister()

LCR.recipeBuilder()
    .fluidInputs(fluid('bast_hofree_hree_concentrate') * 1000)
    .fluidInputs(fluid('sodium_amalgam') * 400)
    .fluidOutputs(fluid('ytterbium_amalgam') * 400)
    .fluidOutputs(fluid('bast_ybfree_hree_concentrate') * 1000)
    .duration(80)
    .EUt(480)
    .buildAndRegister()

ION_EXCHANGE.recipeBuilder()
    .inputs(metaitem('beads.rare_earth_cation_exchange') * 5)
    .fluidInputs(fluid('bast_ybfree_hree_concentrate') * 1000)
    .outputs(metaitem('beads.loaded_thulium_cation_exchange') * 5)
    .fluidOutputs(fluid('bast_tmfree_hree_concentrate') * 1000)
    .duration(400)
    .EUt(16)
    .buildAndRegister()

ION_EXCHANGE.recipeBuilder()
    .inputs(metaitem('beads.rare_earth_cation_exchange') * 8)
    .fluidInputs(fluid('bast_tmfree_hree_concentrate') * 1000)
    .outputs(metaitem('beads.loaded_lutetium_cation_exchange') * 8)
    .fluidOutputs(fluid('bast_hree_waste') * 1000)
    .duration(400)
    .EUt(16)
    .buildAndRegister()