import globals.Globals
import static globals.SinteringGlobals.*

GRAVITY_SEPARATOR = recipemap('gravity_separator')
MIXER = recipemap('mixer')
FROTH_FLOTATION = recipemap('froth_flotation')
CLARIFIER = recipemap('clarifier')
ROASTER = recipemap('roaster')
ROTARY_KILN = recipemap('rotary_kiln')
BR = recipemap('batch_reactor')
BLENDER = recipemap('blender')
FLUIDIZED_BED_REACTOR = recipemap('fluidized_bed_reactor')
ION_EXCHANGE = recipemap('ion_exchange_column')
CENTRIFUGE = recipemap('centrifuge')
LCR = recipemap('large_chemical_reactor')
ELECTROLYTIC_CELL = recipemap('electrolytic_cell')
SIFTER = recipemap('sifter')
VACUUM_CHAMBER = recipemap('vacuum_chamber')
CRYSTALLIZER = recipemap('crystallizer')
MACERATOR = recipemap('macerator')

MACERATOR.recipeBuilder()
    .inputs(item('susy:resource_block', 6))
    .outputs(metaitem('dustMonazite') * 4)
    .duration(240)
    .EUt(7)
    .buildAndRegister()

// Monazite Pre-processing

MIXER.recipeBuilder()
    .inputs(ore('dustMonazite'))
    .fluidInputs(fluid('sulfuric_acid') * 1000)
    .fluidOutputs(fluid('monazite_leach') * 1000)
    .duration(120)
    .EUt(480)
    .buildAndRegister()

SIFTER.recipeBuilder()
    .notConsumable(metaitem('item_filter'))
    .fluidInputs(fluid('monazite_leach') * 1000)
    .chancedOutput(metaitem('dustIlmenite'), 1500, 0)
    .chancedOutput(metaitem('dustZircon'), 500, 0)
    .chancedOutput(metaitem('dustQuartzite'), 1000, 0)
    .fluidOutputs(fluid('sifted_monazite_leach') * 1000)
    .duration(40)
    .EUt(30)
    .buildAndRegister()

CENTRIFUGE.recipeBuilder()
    .fluidInputs(fluid('sifted_monazite_leach') * 1000)
    .fluidInputs(fluid('ammonia_solution') * 1000)
    .outputs(metaitem('dustThoriumHydroxidePrecipitate') * 7)
    .fluidOutputs(fluid('thfree_monazite_leach') * 1000)
    .duration(80)
    .EUt(120)
    .buildAndRegister()

CENTRIFUGE.recipeBuilder()
    .fluidInputs(fluid('thfree_monazite_leach') * 1000)
    .fluidInputs(fluid('ammonia_solution') * 1000)
    .outputs(metaitem('dustMonaReHydroxides'))
    .fluidOutputs(fluid('refree_monazite_leach') * 1000)
    .duration(80)
    .EUt(120)
    .buildAndRegister()

CENTRIFUGE.recipeBuilder()
    .fluidInputs(fluid('refree_monazite_leach') * 1000)
    .fluidInputs(fluid('ammonia_solution') * 1000)
    .outputs(metaitem('dustUranylHydroxidePrecipitate'))
    .fluidOutputs(fluid('monazite_waste') * 1000)
    .duration(80)
    .EUt(120)
    .buildAndRegister()

// Monazite Concentrate Processing

MIXER.recipeBuilder()
    .inputs(ore('dustMonaReHydroxides'))
    .inputs(ore('dustPotassiumPermanganate') * 3)
    .fluidInputs(fluid('nitric_acid') * 5000)
    .fluidOutputs(fluid('mona_ox_re_nitrates_solution') * 1000)
    .duration(80)
    .EUt(120)
    .buildAndRegister()


BLENDER.recipeBuilder()
    .fluidInputs(fluid('mona_ox_re_nitrates_solution') * 1000)
    .fluidInputs(fluid('tributyl_phosphate') * 500)
    .fluidOutputs(fluid('mona_cerium_extract') * 500)
    .fluidOutputs(fluid('mona_cefree_re_nitrates_solution') * 1000)
    .duration(80)
    .EUt(120)
    .buildAndRegister()


BLENDER.recipeBuilder()
    .fluidInputs(fluid('mona_cefree_re_nitrates_solution') * 1000)
    .fluidInputs(fluid('rare_earth_extraction_mixture') * 100)
    .fluidOutputs(fluid('mona_lree_concentrate') * 50)
    .fluidOutputs(fluid('mona_dehpa_extract') * 1000)
    .duration(80)
    .EUt(120)
    .buildAndRegister()


MIXER.recipeBuilder()
    .fluidInputs(fluid('hydrochloric_acid') * 50)
    .fluidInputs(fluid('mona_dehpa_extract') * 1000)
    .fluidOutputs(fluid('rare_earth_extraction_mixture') * 100)
    .fluidOutputs(fluid('mona_re_chlorides_solution') * 1000)
    .duration(80)
    .EUt(120)
    .buildAndRegister()


BLENDER.recipeBuilder()
    .fluidInputs(fluid('mona_re_chlorides_solution') * 1000)
    .fluidInputs(fluid('rare_earth_separation_mixture') * 100)
    .fluidOutputs(fluid('mona_mree_concentrate') * 500)
    .fluidOutputs(fluid('mona_ehehpa_extract') * 1000)
    .duration(80)
    .EUt(120)
    .buildAndRegister()


MIXER.recipeBuilder()
    .fluidInputs(fluid('hydrochloric_acid') * 50)
    .fluidInputs(fluid('mona_ehehpa_extract') * 1000)
    .fluidOutputs(fluid('rare_earth_separation_mixture') * 100)
    .fluidOutputs(fluid('mona_hree_concentrate') * 40)
    .duration(80)
    .EUt(120)
    .buildAndRegister()

// Monazite Element Extraction

MIXER.recipeBuilder()
    .fluidInputs(fluid('mona_cerium_extract') * 1000)
    .fluidInputs(fluid('diluted_hydrochloric_acid') * 10)
    .chancedOutput(metaitem('dustCeriumIvNitrate') * 17, 9100, 0)
    .fluidOutputs(fluid('tributyl_phosphate') * 1000)
    .duration(120)
    .EUt(30)
    .buildAndRegister()

FLUIDIZED_BED_REACTOR.recipeBuilder()
    .inputs(ore('dustAmmoniumCarbonate') * 42)
    .fluidInputs(fluid('mona_lree_concentrate') * 1000)
    .chancedOutput(metaitem('dustLanthanumCarbonate') * 14, 9580, 0)
    .fluidOutputs(fluid('mona_lafree_lree_concentrate') * 1000)
    .duration(40)
    .EUt(120)
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(ore('dustSodiumHydroxide') * 36)
    .fluidInputs(fluid('mona_lafree_lree_concentrate') * 1000)
    .fluidOutputs(fluid('mona_lafree_lree_hydroxides') * 1000)
    .duration(80)
    .EUt(30)
    .buildAndRegister()

MIXER.recipeBuilder()
    .notConsumable(fluid('sodium_hydroxide') * 432)
    .inputs(ore('dustSodiumChlorate') * 5)
    .fluidInputs(fluid('mona_lafree_lree_hydroxides') * 1000)
    .fluidOutputs(fluid('mona_oxidised_lree_hydroxides') * 1000)
    .duration(80)
    .EUt(30)
    .buildAndRegister()

CENTRIFUGE.recipeBuilder()
    .fluidInputs(fluid('mona_oxidised_lree_hydroxides') * 1000)
    .chancedOutput(metaitem('dustPraseodymiumOxide') * 6, 7580, 0)
    .fluidOutputs(fluid('mona_prfree_lree_hydroxides') * 1000)
    .duration(120)
    .EUt(120)
    .buildAndRegister()

MIXER.recipeBuilder()
    .fluidInputs(fluid('distilled_water') * 1000)
    .fluidInputs(fluid('mona_prfree_lree_hydroxides') * 1000)
    .chancedOutput(metaitem('dustNeodymiumHydroxide') * 14, 8020, 0)
    .fluidOutputs(fluid('mona_lree_waste') * 1000)
    .duration(80)
    .EUt(16)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustSmallZinc') * 6)
    .fluidInputs(fluid('mona_mree_concentrate') * 1000)
    .fluidInputs(fluid('sulfuric_acid') * 1000)
    .chancedOutput(metaitem('dustEuropiumIiSulfate') * 6, 5140, 0)
    .fluidOutputs(fluid('mona_eufree_mree_concentrate') * 1000)
    .duration(100)
    .EUt(120)
    .buildAndRegister()

LCR.recipeBuilder()
    .fluidInputs(fluid('mona_eufree_mree_concentrate') * 1000)
    .fluidInputs(fluid('sodium_amalgam') * 480)
    .fluidOutputs(fluid('samarium_amalgam') * 480)
    .fluidOutputs(fluid('mona_smfree_mree_concentrate') * 1000)
    .duration(80)
    .EUt(480)
    .buildAndRegister()

ION_EXCHANGE.recipeBuilder()
    .inputs(metaitem('beads.strong_basic_anion_exchange') * 5)
    .fluidInputs(fluid('mona_smfree_mree_concentrate') * 1000)
    .outputs(metaitem('beads.loaded_gadolinium_anion_exchange') * 5)
    .fluidOutputs(fluid('mona_gdfree_mree_concentrate') * 1000)
    .duration(400)
    .EUt(16)
    .buildAndRegister()

ELECTROLYTIC_CELL.recipeBuilder()
    .inputs(ore('dustPotassiumCarbonate') * 18)
    .notConsumable(metaitem('stickPlatinum'))
    .notConsumable(fluid('potassium_hydroxide_solution') * 432)
    .fluidInputs(fluid('mona_gdfree_mree_concentrate') * 1000)
    .chancedOutput(metaitem('dustTerbiumCarbonate') * 14, 2158, 0)
    .fluidOutputs(fluid('mona_tbfree_mree_concentrate') * 1000)
    .duration(100)
    .EUt(1920)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustSodiumFluoride') * 6)
    .fluidInputs(fluid('mona_tbfree_mree_concentrate') * 1000)
    .chancedOutput(metaitem('dustDysprosiumFluoride') * 4, 4260, 0)
    .fluidOutputs(fluid('mona_mree_waste') * 1000)
    .duration(80)
    .EUt(120)
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('mona_hree_concentrate') * 1000)
    .fluidInputs(fluid('sodium_chromate_solution') * 2000)
    .outputs(metaitem('dustMonaHreeDoubleChromates'))
    .fluidOutputs(fluid('yttrium_chloride_solution') * 875)
    .duration(60)
    .EUt(60)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustMonaHreeDoubleChromates'))
    .fluidInputs(fluid('hydrochloric_acid') * 4000)
    .fluidOutputs(fluid('mona_yfree_hree_concentrate') * 1000)
    .fluidOutputs(fluid('hydrogen') * 2000)
    .duration(60)
    .EUt(60)
    .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
    .notConsumable(fluid('two_ethylhexanol') * 1000)
    .fluidInputs(fluid('mona_yfree_hree_concentrate') * 1000)
    .fluidInputs(fluid('sodium_hydroxide_solution') * 100)
    .fluidInputs(fluid('sodium_dodecyl_sulfate_solution') * 3000)
    .chancedOutput(metaitem('dustErbiumDodecylSulfate'), 4350, 0)
    .fluidOutputs(fluid('mona_erfree_hree_concentrate') * 1000)
    .duration(120)
    .EUt(120)
    .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
    .notConsumable(fluid('two_ethylhexanol') * 1000)
    .fluidInputs(fluid('mona_erfree_hree_concentrate') * 1000)
    .fluidInputs(fluid('sodium_hydroxide_solution') * 100)
    .fluidInputs(fluid('sodium_dodecyl_sulfate_solution') * 3000)
    .chancedOutput(metaitem('dustHolmiumDodecylSulfate'), 4400, 0)
    .fluidOutputs(fluid('mona_hofree_hree_concentrate') * 1000)
    .duration(120)
    .EUt(120)
    .buildAndRegister()

LCR.recipeBuilder()
    .fluidInputs(fluid('mona_hofree_hree_concentrate') * 1000)
    .fluidInputs(fluid('sodium_amalgam') * 335)
    .fluidOutputs(fluid('ytterbium_amalgam') * 335)
    .fluidOutputs(fluid('mona_ybfree_hree_concentrate') * 1000)
    .duration(80)
    .EUt(480)
    .buildAndRegister()

ION_EXCHANGE.recipeBuilder()
    .inputs(metaitem('beads.rare_earth_cation_exchange') * 3)
    .fluidInputs(fluid('mona_ybfree_hree_concentrate') * 1000)
    .outputs(metaitem('beads.loaded_thulium_cation_exchange') * 3)
    .fluidOutputs(fluid('mona_tmfree_hree_concentrate') * 1000)
    .duration(400)
    .EUt(16)
    .buildAndRegister()

ION_EXCHANGE.recipeBuilder()
    .inputs(metaitem('beads.rare_earth_cation_exchange') * 5)
    .fluidInputs(fluid('mona_tmfree_hree_concentrate') * 1000)
    .outputs(metaitem('beads.loaded_lutetium_cation_exchange') * 5)
    .fluidOutputs(fluid('mona_hree_waste') * 1000)
    .duration(400)
    .EUt(16)
    .buildAndRegister()