import globals.Globals
import static globals.SinteringGlobals.*

GRAVITY_SEPARATOR = recipemap('gravity_separator')
MIXER = recipemap('mixer')
FROTH_FLOTATION = recipemap('froth_flotation')
CLARIFIER = recipemap('clarifier')
ROASTER = recipemap('roaster')
ROTARY_KILN = recipemap('rotary_kiln')
BR = recipemap('batch_reactor')
BLENDER = recipemap('blender')
FLUIDIZED_BED_REACTOR = recipemap('fluidized_bed_reactor')
ION_EXCHANGE = recipemap('ion_exchange_column')
CENTRIFUGE = recipemap('centrifuge')
LCR = recipemap('large_chemical_reactor')
ELECTROLYTIC_CELL = recipemap('electrolytic_cell')
SIFTER = recipemap('sifter')
VACUUM_CHAMBER = recipemap('vacuum_chamber')
CRYSTALLIZER = recipemap('crystallizer')
MACERATOR = recipemap('macerator')

MACERATOR.recipeBuilder()
    .inputs(item('susy:resource_block', 9))
    .outputs(metaitem('dustXenotime') * 4)
    .duration(240)
    .EUt(7)
    .buildAndRegister()

// Xenotime Pre-processing

for (fuel in sintering_fuels) {
    if (!fuel.isPlasma) {
        ROTARY_KILN.recipeBuilder()
            .inputs(ore('dustSodaAsh') * 24)
            .inputs(ore('dustXenotime'))
            .fluidInputs(fluid(fuel.name) * fuel.amountRequired)
            .fluidInputs(fluid('oxygen') * 50)
            .outputs(metaitem('dustRoastedXenotime'))
            .fluidOutputs(fluid('carbon_dioxide') * 4000)
            .duration(400)
            .EUt(Globals.voltAmps[2])
            .buildAndRegister()
    }
}

MIXER.recipeBuilder()
    .inputs(ore('dustRoastedXenotime'))
    .fluidInputs(fluid('distilled_water') * 4000)
    .fluidOutputs(fluid('xenotime_slurry') * 4000)
    .duration(100)
    .EUt(30)
    .buildAndRegister()

VACUUM_CHAMBER.recipeBuilder()
    .notConsumable(metaitem('item_filter'))
    .fluidInputs(fluid('xenotime_slurry') * 4000)
    .outputs(metaitem('dustXenotimeResidue'))
    .fluidOutputs(fluid('xenotime_phosphate_waste') * 4000)
    .duration(160)
    .EUt(80)
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(ore('dustXenotimeResidue'))
    .fluidInputs(fluid('nitric_acid') * 1000)
    .fluidOutputs(fluid('crude_xenotime_nitrate_solution') * 1000)
    .duration(80)
    .EUt(120)
    .buildAndRegister()

VACUUM_CHAMBER.recipeBuilder()
    .notConsumable(metaitem('item_filter'))
    .fluidInputs(fluid('crude_xenotime_nitrate_solution') * 1000)
    .chancedOutput(metaitem('dustXenotimeTailing'), 1000, 0)
    .fluidOutputs(fluid('xeno_re_nitrates_solution') * 1000)
    .duration(100)
    .EUt(80)
    .buildAndRegister()

SIFTER.recipeBuilder()
    .inputs(ore('dustXenotimeTailing'))
    .chancedOutput(metaitem('dustCassiterite') * 3, 500, 0)
    .chancedOutput(metaitem('dustThoriumDioxide') * 3, 500, 0)
    .chancedOutput(metaitem('dustUraniumDioxide') * 3, 500, 0)
    .duration(100)
    .EUt(30)
    .buildAndRegister()

// Xenotime Concentrate Processing

MIXER.recipeBuilder()
    .inputs(ore('dustPotassiumPermanganate') * 1)
    .fluidInputs(fluid('nitric_acid') * 1150)
    .fluidInputs(fluid('xeno_re_nitrates_solution') * 1000)
    .fluidOutputs(fluid('xeno_ox_re_nitrates_solution') * 1000)
    .duration(80)
    .EUt(120)
    .buildAndRegister()


BLENDER.recipeBuilder()
    .fluidInputs(fluid('xeno_ox_re_nitrates_solution') * 1000)
    .fluidInputs(fluid('tributyl_phosphate') * 100)
    .fluidOutputs(fluid('xeno_cerium_extract') * 100)
    .fluidOutputs(fluid('xeno_cefree_re_nitrates_solution') * 1000)
    .duration(80)
    .EUt(120)
    .buildAndRegister()


BLENDER.recipeBuilder()
    .fluidInputs(fluid('xeno_cefree_re_nitrates_solution') * 1000)
    .fluidInputs(fluid('rare_earth_extraction_mixture') * 100)
    .fluidOutputs(fluid('xeno_lree_concentrate') * 20)
    .fluidOutputs(fluid('xeno_dehpa_extract') * 1000)
    .duration(80)
    .EUt(120)
    .buildAndRegister()


MIXER.recipeBuilder()
    .fluidInputs(fluid('hydrochloric_acid') * 50)
    .fluidInputs(fluid('xeno_dehpa_extract') * 1000)
    .fluidOutputs(fluid('rare_earth_extraction_mixture') * 100)
    .fluidOutputs(fluid('xeno_re_chlorides_solution') * 1000)
    .duration(80)
    .EUt(120)
    .buildAndRegister()


BLENDER.recipeBuilder()
    .fluidInputs(fluid('xeno_re_chlorides_solution') * 1000)
    .fluidInputs(fluid('rare_earth_separation_mixture') * 100)
    .fluidOutputs(fluid('xeno_mree_concentrate') * 100)
    .fluidOutputs(fluid('xeno_ehehpa_extract') * 1000)
    .duration(80)
    .EUt(120)
    .buildAndRegister()


MIXER.recipeBuilder()
    .fluidInputs(fluid('hydrochloric_acid') * 50)
    .fluidInputs(fluid('xeno_ehehpa_extract') * 1000)
    .fluidOutputs(fluid('rare_earth_separation_mixture') * 100)
    .fluidOutputs(fluid('xeno_hree_concentrate') * 200)
    .duration(80)
    .EUt(120)
    .buildAndRegister()

// Xenotime Element Extraction

MIXER.recipeBuilder()
    .fluidInputs(fluid('xeno_cerium_extract') * 1000)
    .fluidInputs(fluid('diluted_hydrochloric_acid') * 10)
    .chancedOutput(metaitem('dustCeriumIvNitrate') * 17, 6400, 0)
    .fluidOutputs(fluid('tributyl_phosphate') * 1000)
    .duration(120)
    .EUt(30)
    .buildAndRegister()

FLUIDIZED_BED_REACTOR.recipeBuilder()
    .inputs(ore('dustAmmoniumCarbonate') * 42)
    .fluidInputs(fluid('xeno_lree_concentrate') * 1000)
    .chancedOutput(metaitem('dustLanthanumCarbonate') * 14, 6000, 0)
    .fluidOutputs(fluid('xeno_lafree_lree_concentrate') * 1000)
    .duration(40)
    .EUt(120)
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(ore('dustSodiumHydroxide') * 18)
    .fluidInputs(fluid('xeno_lafree_lree_concentrate') * 1000)
    .fluidOutputs(fluid('xeno_lafree_lree_hydroxides') * 1000)
    .duration(80)
    .EUt(30)
    .buildAndRegister()

MIXER.recipeBuilder()
    .notConsumable(fluid('sodium_hydroxide') * 432)
    .inputs(ore('dustSodiumChlorate') * 5)
    .fluidInputs(fluid('xeno_lafree_lree_hydroxides') * 1000)
    .fluidOutputs(fluid('xeno_oxidised_lree_hydroxides') * 1000)
    .duration(80)
    .EUt(30)
    .buildAndRegister()

CENTRIFUGE.recipeBuilder()
    .fluidInputs(fluid('xeno_oxidised_lree_hydroxides') * 1000)
    .chancedOutput(metaitem('dustPraseodymiumOxide') * 3, 5000, 0)
    .fluidOutputs(fluid('xeno_prfree_lree_hydroxides') * 1000)
    .duration(120)
    .EUt(120)
    .buildAndRegister()

MIXER.recipeBuilder()
    .fluidInputs(fluid('distilled_water') * 1000)
    .fluidInputs(fluid('xeno_prfree_lree_hydroxides') * 1000)
    .outputs(metaitem('dustNeodymiumHydroxide') * 7)
    .fluidOutputs(fluid('xeno_lree_waste'))
    .duration(80)
    .EUt(16)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustSmallZinc') * 6)
    .fluidInputs(fluid('xeno_mree_concentrate') * 1000)
    .fluidInputs(fluid('sulfuric_acid') * 1000)
    .chancedOutput(metaitem('dustEuropiumIiSulfate') * 6, 8000, 0)
    .fluidOutputs(fluid('xeno_eufree_mree_concentrate') * 1000)
    .duration(100)
    .EUt(120)
    .buildAndRegister()

LCR.recipeBuilder()
    .fluidInputs(fluid('xeno_eufree_mree_concentrate') * 1000)
    .fluidInputs(fluid('sodium_amalgam') * 800)
    .fluidOutputs(fluid('samarium_amalgam') * 800)
    .fluidOutputs(fluid('xeno_smfree_mree_concentrate') * 1000)
    .duration(80)
    .EUt(480)
    .buildAndRegister()

ION_EXCHANGE.recipeBuilder()
    .inputs(metaitem('beads.strong_basic_anion_exchange') * 8)
    .fluidInputs(fluid('xeno_smfree_mree_concentrate') * 1000)
    .outputs(metaitem('beads.loaded_gadolinium_anion_exchange') * 8)
    .fluidOutputs(fluid('xeno_gdfree_mree_concentrate') * 1000)
    .duration(400)
    .EUt(16)
    .buildAndRegister()

ELECTROLYTIC_CELL.recipeBuilder()
    .inputs(ore('dustPotassiumCarbonate') * 18)
    .notConsumable(metaitem('stickPlatinum'))
    .notConsumable(fluid('potassium_hydroxide_solution') * 432)
    .fluidInputs(fluid('xeno_gdfree_mree_concentrate') * 1000)
    .chancedOutput(metaitem('dustTerbiumCarbonate') * 14, 3500, 0)
    .fluidOutputs(fluid('xeno_tbfree_mree_concentrate') * 1000)
    .duration(100)
    .EUt(1920)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustSodiumFluoride') * 6)
    .fluidInputs(fluid('xeno_tbfree_mree_concentrate') * 1000)
    .chancedOutput(metaitem('dustDysprosiumFluoride') * 4, 7200, 0)
    .fluidOutputs(fluid('xeno_mree_waste') * 1000)
    .duration(80)
    .EUt(120)
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('xeno_hree_concentrate') * 1000)
    .fluidInputs(fluid('sodium_chromate_solution') * 2000)
    .outputs(metaitem('dustXenoHreeDoubleChromates'))
    .fluidOutputs(fluid('yttrium_chloride_solution') * 800)
    .duration(60)
    .EUt(60)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustXenoHreeDoubleChromates'))
    .fluidInputs(fluid('hydrochloric_acid') * 800)
    .fluidOutputs(fluid('xeno_yfree_hree_concentrate') * 200)
    .fluidOutputs(fluid('hydrogen') * 400)
    .duration(60)
    .EUt(60)
    .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
    .notConsumable(fluid('two_ethylhexanol') * 1000)
    .fluidInputs(fluid('xeno_yfree_hree_concentrate') * 1000)
    .fluidInputs(fluid('sodium_hydroxide_solution') * 100)
    .fluidInputs(fluid('sodium_dodecyl_sulfate_solution') * 3000)
    .chancedOutput(metaitem('dustErbiumDodecylSulfate'), 8000, 0)
    .fluidOutputs(fluid('xeno_erfree_hree_concentrate') * 1000)
    .duration(120)
    .EUt(120)
    .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
    .notConsumable(fluid('two_ethylhexanol') * 1000)
    .fluidInputs(fluid('xeno_erfree_hree_concentrate') * 1000)
    .fluidInputs(fluid('sodium_hydroxide_solution') * 100)
    .fluidInputs(fluid('sodium_dodecyl_sulfate_solution') * 3000)
    .chancedOutput(metaitem('dustHolmiumDodecylSulfate'), 7000, 0)
    .fluidOutputs(fluid('xeno_hofree_hree_concentrate') * 1000)
    .duration(120)
    .EUt(120)
    .buildAndRegister()

LCR.recipeBuilder()
    .fluidInputs(fluid('xeno_hofree_hree_concentrate') * 1000)
    .fluidInputs(fluid('sodium_amalgam') * 600)
    .fluidOutputs(fluid('ytterbium_amalgam') * 600)
    .fluidOutputs(fluid('xeno_ybfree_hree_concentrate') * 1000)
    .duration(80)
    .EUt(480)
    .buildAndRegister()

ION_EXCHANGE.recipeBuilder()
    .inputs(metaitem('beads.rare_earth_cation_exchange') * 7)
    .fluidInputs(fluid('xeno_ybfree_hree_concentrate') * 1000)
    .outputs(metaitem('beads.loaded_thulium_cation_exchange') * 7)
    .fluidOutputs(fluid('xeno_tmfree_hree_concentrate') * 1000)
    .duration(400)
    .EUt(16)
    .buildAndRegister()

ION_EXCHANGE.recipeBuilder()
    .inputs(metaitem('beads.rare_earth_cation_exchange') * 7)
    .fluidInputs(fluid('xeno_tmfree_hree_concentrate') * 1000)
    .outputs(metaitem('beads.loaded_lutetium_cation_exchange') * 7)
    .fluidOutputs(fluid('xeno_hree_waste') * 1000)
    .duration(400)
    .EUt(16)
    .buildAndRegister()