BR = recipemap('batch_reactor')
ROASTER = recipemap('roaster')

ROASTER.recipeBuilder()
        .inputs(ore('dustThoriumOxalate') * 13)
        .outputs(metaitem('dustThoriumDioxide') * 3)
        .fluidOutputs(fluid('carbon_dioxide') * 2000)
        .fluidOutputs(fluid('carbon_monoxide') * 2000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()

BR.recipeBuilder()
        .inputs(ore('dustThoriumHydroxidePrecipitate'))
        .fluidInputs(fluid('tributyl_phosphate') * 50)
        .outputs(metaitem('dustUraniumDioxide') * 3)
        .chancedOutput(metaitem('dustMonaReHydroxides'), 100, 0)
        .fluidOutputs(fluid('tributyl_phosphate') * 50)
        .duration(80)
        .EUt(120)
        .buildAndRegister()