BR = recipemap('batch_reactor')
CENTRIFUGE = recipemap('centrifuge')
ROASTER = recipemap('roaster')

BR.recipeBuilder()
    .inputs(ore('dustThoriumConcentrate'))
    .fluidInputs(fluid('sodium_hydroxide_solution') * 470)
    .outputs(metaitem('dustDigestedThoriumConcentrate'))
    .fluidOutputs(fluid('wastewater') * 470)
    .duration(80)
    .EUt(120)
    .buildAndRegister()

BR.recipeBuilder()
    .inputs(ore('dustDigestedThoriumConcentrate'))
    .fluidInputs(fluid('nitric_acid') * 470)
    .fluidOutputs(fluid('dissolved_thorium_concentrate') * 705)
    .duration(80)
    .EUt(120)
    .buildAndRegister()

CENTRIFUGE.recipeBuilder()
    .inputs(ore('dustSmallSodiumHydroxide'))
    .fluidInputs(fluid('dissolved_thorium_concentrate') * 705)
    .fluidInputs(fluid('tributyl_phosphate') * 160)
    .chancedOutput(metaitem('dustMonaReHydroxides'), 500, 0)
    .fluidOutputs(fluid('thorium_extract') * 160)
    .duration(80)
    .EUt(120)
    .buildAndRegister()

CENTRIFUGE.recipeBuilder()
    .fluidInputs(fluid('thorium_extract') * 160)
    .fluidInputs(fluid('distilled_water') * 80)
    .fluidOutputs(fluid('tributyl_phosphate') * 160)
    .fluidOutputs(fluid('thorium_nitrate_solution') * 80)
    .duration(80)
    .EUt(120)
    .buildAndRegister()

ROASTER.recipeBuilder()
    .fluidInputs(fluid('thorium_nitrate_solution') * 1000)
    .outputs(metaitem('dustThoriumDioxide') * 3)
    .fluidOutputs(fluid('nitrogen_dioxide') * 2000)
    .fluidOutputs(fluid('oxygen') * 2000)
    .duration(80)
    .EUt(120)
    .buildAndRegister() 