import globals.Globals
import static globals.SinteringGlobals.*

import static gregtech.api.unification.material.Materials.*;
import gregtech.api.unification.material.MarkerMaterials;
import static gregtech.api.unification.ore.OrePrefix.dye;

GRAVITY_SEPARATOR = recipemap('gravity_separator')
MIXER = recipemap('mixer')
FROTH_FLOTATION = recipemap('froth_flotation')
CLARIFIER = recipemap('clarifier')
ROASTER = recipemap('roaster')
ROTARY_KILN = recipemap('rotary_kiln')
BR = recipemap('batch_reactor')
BLENDER = recipemap('blender')
FLUIDIZED_BED_REACTOR = recipemap('fluidized_bed_reactor')
ION_EXCHANGE = recipemap('ion_exchange_column')
CENTRIFUGE = recipemap('centrifuge')
LCR = recipemap('large_chemical_reactor')
ELECTROLYTIC_CELL = recipemap('electrolytic_cell')
SIFTER = recipemap('sifter')
VACUUM_CHAMBER = recipemap('vacuum_chamber')


mods.gregtech.macerator.recipeBuilder()
        .inputs(item('susy:resource_block', 7))
        .outputs(metaitem('dustBastnasite') * 4)
        .duration(240)
        .EUt(7)
        .buildAndRegister()

mods.gregtech.macerator.recipeBuilder()
        .inputs(item('susy:resource_block', 6))
        .outputs(metaitem('dustMonazite') * 4)
        .duration(240)
        .EUt(7)
        .buildAndRegister()

mods.gregtech.macerator.recipeBuilder()
        .inputs(item('susy:resource_block', 9))
        .outputs(metaitem('dustXenotime') * 4)
        .duration(240)
        .EUt(7)
        .buildAndRegister()

// Bastnasite Pre-processing

GRAVITY_SEPARATOR.recipeBuilder()
        .inputs(ore('dustBastnasite'))
        .outputs(metaitem('dustSiftedBastnasite'))
        .duration(40)
        .EUt(30)
        .buildAndRegister()

MIXER.recipeBuilder()
        .inputs(ore('dustSiftedBastnasite') * 8)
        .fluidInputs(fluid('distilled_water') * 2000)
        .fluidOutputs(fluid('impure_bastnasite_slurry') * 2000)
        .duration(80)
        .EUt(480)
        .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
        .notConsumable(fluid('methyl_isobutyl_carbinol') * 100)
        .notConsumable(fluid('oleic_acid') * 1000)
        .fluidInputs(fluid('impure_bastnasite_slurry') * 2000)
        .fluidOutputs(fluid('bastnasite_slurry') * 2000)
        .duration(80)
        .EUt(480)
        .buildAndRegister()

CLARIFIER.recipeBuilder()
        .fluidInputs(fluid('bastnasite_slurry') * 2000)
        .outputs(metaitem('dustFlotatedBastnasite') * 8)
        .fluidOutputs(fluid('wastewater') * 2000)
        .duration(20)
        .EUt(30)
        .buildAndRegister()

ROASTER.recipeBuilder()
        .inputs(ore('dustFlotatedBastnasite'))
        .fluidInputs(fluid('sulfuric_acid') * 6000)
        .fluidOutputs(fluid('hydrogen_fluoride') * 30)
        .fluidOutputs(fluid('roasted_bastnasite_leach') * 6000)
        .duration(40)
        .EUt(120)
        .buildAndRegister()


for (fuel in sintering_fuels) {
    if (!fuel.isPlasma) {
        ROTARY_KILN.recipeBuilder()
                .inputs(ore('dustSodaAsh') * 24)
                .fluidInputs(fluid(fuel.name) * fuel.amountRequired)
                .fluidInputs(fluid('oxygen') * 50)
                .fluidInputs(fluid('roasted_bastnasite_leach') * 6000)
                .outputs(metaitem('dustConcentratedBastnasite'))
                .fluidOutputs(fluid('carbon_dioxide') * 4000)
                .duration(400)
                .EUt(Globals.voltAmps[2])
                .buildAndRegister()
    }
}

BR.recipeBuilder()
        .inputs(ore('dustConcentratedBastnasite'))
        .fluidInputs(fluid('sodium_hydroxide_solution') * 2000)
        .outputs(metaitem('dustBastReHydroxides'))
        .fluidOutputs(fluid('sodium_sulfate_solution') * 6000)
        .duration(100)
        .EUt(30)
        .buildAndRegister()

// Monazite Pre-processing

MIXER.recipeBuilder()
        .inputs(ore('dustMonazite'))
        .fluidInputs(fluid('sulfuric_acid') * 1000)
        .fluidOutputs(fluid('monazite_leach') * 1000)
        .duration(120)
        .EUt(480)
        .buildAndRegister()

SIFTER.recipeBuilder()
        .notConsumable(metaitem('item_filter'))
        .fluidInputs(fluid('monazite_leach') * 1000)
        .chancedOutput(metaitem('dustIlmenite'), 1500, 0)
        .chancedOutput(metaitem('dustZircon'), 500, 0)
        .chancedOutput(metaitem('dustQuartzite'), 1000, 0)
        .fluidOutputs(fluid('sifted_monazite_leach') * 1000)
        .duration(40)
        .EUt(30)
        .buildAndRegister()

CENTRIFUGE.recipeBuilder()
        .fluidInputs(fluid('sifted_monazite_leach') * 1000)
        .fluidInputs(fluid('ammonia_solution') * 1000)
        .outputs(metaitem('dustThoriumHydroxidePrecipitate') * 7)
        .fluidOutputs(fluid('thfree_monazite_leach') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()

CENTRIFUGE.recipeBuilder()
        .fluidInputs(fluid('thfree_monazite_leach') * 1000)
        .fluidInputs(fluid('ammonia_solution') * 1000)
        .outputs(metaitem('dustMonaReHydroxides'))
        .fluidOutputs(fluid('refree_monazite_leach') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()

CENTRIFUGE.recipeBuilder()
        .fluidInputs(fluid('refree_monazite_leach') * 1000)
        .fluidInputs(fluid('ammonia_solution') * 1000)
        .outputs(metaitem('dustUranylHydroxidePrecipitate') * 1000)
        .fluidOutputs(fluid('monazite_waste') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()

// Xenotime Pre-processing

for (fuel in sintering_fuels) {
    if (!fuel.isPlasma) {
        ROTARY_KILN.recipeBuilder()
                .inputs(ore('dustSodaAsh') * 24)
                .inputs(ore('dustXenotime'))
                .fluidInputs(fluid(fuel.name) * fuel.amountRequired)
                .fluidInputs(fluid('oxygen') * 50)
                .outputs(metaitem('dustRoastedXenotime'))
                .fluidOutputs(fluid('carbon_dioxide'))
                .duration(400)
                .EUt(Globals.voltAmps[2])
                .buildAndRegister()
    }
}

MIXER.recipeBuilder()
        .inputs(ore('dustRoastedXenotime'))
        .fluidInputs(fluid('distilled_water') * 4000)
        .fluidOutputs(fluid('xenotime_slurry') * 4000)
        .duration(100)
        .EUt(30)
        .buildAndRegister()

VACUUM_CHAMBER.recipeBuilder()
        .notConsumable(metaitem('item_filter'))
        .fluidInputs(fluid('xenotime_slurry') * 4000)
        .outputs(metaitem('dustXenotimeResidue'))
        .fluidOutputs(fluid('xenotime_phosphate_waste') * 4000)
        .duration(160)
        .EUt(80)
        .buildAndRegister()

MIXER.recipeBuilder()
        .inputs(ore('dustXenotimeResidue'))
        .fluidInputs(fluid('nitric_acid') * 1000)
        .fluidOutputs(fluid('crude_xenotime_nitrate_solution') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()

VACUUM_CHAMBER.recipeBuilder()
        .notConsumable(metaitem('item_filter'))
        .fluidInputs(fluid('crude_xenotime_nitrate_solution') * 1000)
        .chancedOutput(metaitem('dustXenotimeTailing'), 1000, 0)
        .fluidOutputs(fluid('xeno_re_nitrates_solution') * 1000)
        .duration(100)
        .EUt(80)
        .buildAndRegister()

SIFTER.recipeBuilder()
        .inputs(ore('dustXenotimeTailing'))
        .chancedOutput(metaitem('dustCassiterite') * 3, 500, 0)
        .chancedOutput(metaitem('dustThoriumDioxide') * 3, 500, 0)
        .chancedOutput(metaitem('dustUraniumDioxide') * 3, 500, 0)
        .duration(100)
        .EUt(30)
        .buildAndRegister()

// Bastnasite Concentrate Processing

MIXER.recipeBuilder()
        .inputs(ore('dustBastReHydroxides'))
        .fluidInputs(fluid('nitric_acid') * 1000)
        .fluidOutputs(fluid('bast_re_nitrates_solution') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()

MIXER.recipeBuilder()
        .inputs(ore('dustTinyPotassiumPermanganate'))
        .fluidInputs(fluid('nitric_acid') * 100)
        .fluidInputs(fluid('bast_re_nitrates_solution') * 1000)
        .fluidOutputs(fluid('bast_ox_re_nitrates_solution') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()

BLENDER.recipeBuilder()
        .fluidInputs(fluid('bast_ox_re_nitrates_solution') * 1000)
        .fluidInputs(fluid('tributyl_phosphate') * 1000)
        .fluidOutputs(fluid('bast_cerium_extract') * 1000)
        .fluidOutputs(fluid('bast_cefree_re_nitrates_solution') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()

BLENDER.recipeBuilder()
        .fluidInputs(fluid('bast_cefree_re_nitrates_solution') * 1000)
        .fluidInputs(fluid('rare_earth_extraction_mixture') * 100)
        .fluidOutputs(fluid('bast_lree_concentrate') * 250)
        .fluidOutputs(fluid('bast_dehpa_extract') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()

MIXER.recipeBuilder()
        .fluidInputs(fluid('hydrochloric_acid') * 50)
        .fluidInputs(fluid('bast_dehpa_extract') * 1000)
        .fluidOutputs(fluid('rare_earth_extraction_mixture') * 100)
        .fluidOutputs(fluid('bast_re_chlorides_solution') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()

BLENDER.recipeBuilder()
        .fluidInputs(fluid('bast_re_chlorides_solution') * 1000)
        .fluidInputs(fluid('rare_earth_separation_mixture') * 100)
        .fluidOutputs(fluid('bast_mree_concentrate') * 125)
        .fluidOutputs(fluid('bast_ehehpa_extract') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()

MIXER.recipeBuilder()
        .fluidInputs(fluid('hydrochloric_acid') * 50)
        .fluidInputs(fluid('bast_ehehpa_extract') * 1000)
        .fluidOutputs(fluid('rare_earth_separation_mixture') * 100)
        .fluidOutputs(fluid('bast_hree_concentrate') * 20)
        .duration(80)
        .EUt(120)
        .buildAndRegister()

// Monazite Concentrate Processing

MIXER.recipeBuilder()
        .inputs(ore('dustMonaReHydroxides'))
        .fluidInputs(fluid('nitric_acid') * 1000)
        .fluidOutputs(fluid('mona_re_nitrates_solution') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()


MIXER.recipeBuilder()
        .inputs(ore('dustTinyPotassiumPermanganate'))
        .fluidInputs(fluid('nitric_acid') * 100)
        .fluidInputs(fluid('mona_re_nitrates_solution') * 1000)
        .fluidOutputs(fluid('mona_ox_re_nitrates_solution') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()


BLENDER.recipeBuilder()
        .fluidInputs(fluid('mona_ox_re_nitrates_solution') * 1000)
        .fluidInputs(fluid('tributyl_phosphate') * 500)
        .fluidOutputs(fluid('mona_cerium_extract') * 500)
        .fluidOutputs(fluid('mona_cefree_re_nitrates_solution') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()


BLENDER.recipeBuilder()
        .fluidInputs(fluid('mona_cefree_re_nitrates_solution') * 1000)
        .fluidInputs(fluid('rare_earth_extraction_mixture') * 100)
        .fluidOutputs(fluid('mona_lree_concentrate') * 50)
        .fluidOutputs(fluid('mona_dehpa_extract') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()


MIXER.recipeBuilder()
        .fluidInputs(fluid('hydrochloric_acid') * 50)
        .fluidInputs(fluid('mona_dehpa_extract') * 1000)
        .fluidOutputs(fluid('rare_earth_extraction_mixture') * 100)
        .fluidOutputs(fluid('mona_re_chlorides_solution') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()


BLENDER.recipeBuilder()
        .fluidInputs(fluid('mona_re_chlorides_solution') * 1000)
        .fluidInputs(fluid('rare_earth_separation_mixture') * 100)
        .fluidOutputs(fluid('mona_mree_concentrate') * 500)
        .fluidOutputs(fluid('mona_ehehpa_extract') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()


MIXER.recipeBuilder()
        .fluidInputs(fluid('hydrochloric_acid') * 50)
        .fluidInputs(fluid('mona_ehehpa_extract') * 1000)
        .fluidOutputs(fluid('rare_earth_separation_mixture') * 100)
        .fluidOutputs(fluid('mona_hree_concentrate') * 40)
        .duration(80)
        .EUt(120)
        .buildAndRegister()

// Xenotime Concentrate Processing

MIXER.recipeBuilder()
        .inputs(ore('dustTinyPotassiumPermanganate'))
        .fluidInputs(fluid('nitric_acid') * 1000)
        .fluidInputs(fluid('xeno_re_nitrates_solution') * 1000)
        .fluidOutputs(fluid('xeno_ox_re_nitrates_solution') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()


BLENDER.recipeBuilder()
        .fluidInputs(fluid('xeno_ox_re_nitrates_solution') * 1000)
        .fluidInputs(fluid('tributyl_phosphate') * 100)
        .fluidOutputs(fluid('xeno_cerium_extract') * 100)
        .fluidOutputs(fluid('xeno_cefree_re_nitrates_solution') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()


BLENDER.recipeBuilder()
        .fluidInputs(fluid('xeno_cefree_re_nitrates_solution') * 1000)
        .fluidInputs(fluid('rare_earth_extraction_mixture') * 1000)
        .fluidOutputs(fluid('xeno_lree_concentrate') * 20)
        .fluidOutputs(fluid('xeno_dehpa_extract') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()


MIXER.recipeBuilder()
        .fluidInputs(fluid('hydrochloric_acid') * 50)
        .fluidInputs(fluid('xeno_dehpa_extract') * 1000)
        .fluidOutputs(fluid('rare_earth_extraction_mixture') * 1000)
        .fluidOutputs(fluid('xeno_re_chlorides_solution') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()


BLENDER.recipeBuilder()
        .fluidInputs(fluid('xeno_re_chlorides_solution') * 1000)
        .fluidInputs(fluid('rare_earth_separation_mixture') * 100)
        .fluidOutputs(fluid('xeno_mree_concentrate') * 100)
        .fluidOutputs(fluid('xeno_ehehpa_extract') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()


MIXER.recipeBuilder()
        .fluidInputs(fluid('hydrochloric_acid') * 50)
        .fluidInputs(fluid('xeno_ehehpa_extract') * 1000)
        .fluidOutputs(fluid('rare_earth_separation_mixture') * 100)
        .fluidOutputs(fluid('xeno_hree_concentrate') * 200)
        .duration(80)
        .EUt(120)
        .buildAndRegister()


// Bastnasite Element Extraction

MIXER.recipeBuilder()
        .fluidInputs(fluid('bast_cerium_extract') * 1000)
        .fluidInputs(fluid('diluted_hydrochloric_acid') * 10)
        .chancedOutput(metaitem('dustCeriumIvNitrate') * 17, 5200, 0)
        .fluidOutputs(fluid('tributyl_phosphate') * 1000)
        .duration(120)
        .EUt(30)
        .buildAndRegister()

FLUIDIZED_BED_REACTOR.recipeBuilder()
        .inputs(ore('dustAmmoniumCarbonate') * 14)
        .fluidInputs(fluid('bast_lree_concentrate') * 1000)
        .chancedOutput(metaitem('dustLanthanumCarbonate') * 14, 5200, 0)
        .fluidOutputs(fluid('bast_lafree_lree_concentrate') * 1000)
        .duration(40)
        .EUt(120)
        .buildAndRegister()

MIXER.recipeBuilder()
        .inputs(ore('dustSodiumHydroxide') * 3)
        .fluidInputs(fluid('bast_lafree_lree_concentrate') * 1000)
        .fluidOutputs(fluid('bast_lafree_lree_hydroxides') * 1000)
        .duration(80)
        .EUt(30)
        .buildAndRegister()

MIXER.recipeBuilder()
        .notConsumable(fluid('sodium_hydroxide') * 432)
        .inputs(ore('dustSodiumChlorate') * 5)
        .fluidInputs(fluid('bast_lafree_lree_hydroxides') * 1000)
        .fluidOutputs(fluid('bast_oxidised_lree_hydroxides') * 1000)
        .duration(80)
        .EUt(30)
        .buildAndRegister()

CENTRIFUGE.recipeBuilder()
        .fluidInputs(fluid('bast_oxidised_lree_hydroxides') * 1000)
        .chancedOutput(metaitem('dustPraseodymiumOxide') * 5, 4800, 0)
        .fluidOutputs(fluid('bast_prfree_lree_hydroxides') * 1000)
        .duration(120)
        .EUt(120)
        .buildAndRegister()

MIXER.recipeBuilder()
        .fluidInputs(fluid('distilled_water') * 1000)
        .fluidInputs(fluid('bast_prfree_lree_hydroxides') * 1000)
        .chancedOutput(metaitem('dustNeodymiumOxide') * 5, 9600, 0)
        .fluidOutputs(fluid('bast_lree_waste') * 1000)
        .duration(80)
        .EUt(16)
        .buildAndRegister()

BR.recipeBuilder()
        .inputs(ore('dustZinc'))
        .fluidInputs(fluid('bast_mree_concentrate') * 1000)
        .fluidInputs(fluid('sulfuric_acid') * 1720)
        .chancedOutput(metaitem('dustEuropiumIiSulfate') * 6, 7200, 0)
        .fluidOutputs(fluid('bast_eufree_mree_concentrate') * 1000)
        .duration(100)
        .EUt(120)
        .buildAndRegister()

LCR.recipeBuilder()
        .fluidInputs(fluid('bast_eufree_mree_concentrate') * 1000)
        .fluidInputs(fluid('sodium_amalgam') * 800)
        .fluidOutputs(fluid('samarium_amalgam') * 800)
        .fluidOutputs(fluid('chlorine') * 2400)
        .fluidOutputs(fluid('bast_smfree_mree_concentrate') * 1000)
        .duration(80)
        .EUt(480)
        .buildAndRegister()

ION_EXCHANGE.recipeBuilder()
        .inputs(metaitem('beads.strong_basic_anion_exchange') * 7)
        .fluidInputs(fluid('bast_smfree_mree_concentrate') * 1000)
        .outputs(metaitem('beads.loaded_gadolinium_anion_exchange') * 7)
        .fluidOutputs(fluid('bast_gdfree_mree_concentrate') * 1000)
        .duration(400)
        .EUt(16)
        .buildAndRegister()

ELECTROLYTIC_CELL.recipeBuilder()
        .inputs(ore('dustPotassiumCarbonate') * 6)
        .notConsumable(metaitem('stickPlatinum'))
        .notConsumable(fluid('potassium_hydroxide_solution') * 432)
        .fluidInputs(fluid('bast_gdfree_mree_concentrate') * 1000)
        .chancedOutput(metaitem('dustTerbiumCarbonate') * 14, 3040, 0)
        .fluidOutputs(fluid('bast_tbfree_mree_concentrate') * 1000)
        .duration(100)
        .EUt(1920)
        .buildAndRegister()

BR.recipeBuilder()
        .inputs(ore('dustSodiumFluoride') * 2)
        .fluidInputs(fluid('bast_tbfree_mree_concentrate') * 1000)
        .chancedOutput(metaitem('dustDysprosiumFluoride') * 4, 6080, 0)
        .fluidOutputs(fluid('bast_mree_waste') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()

BR.recipeBuilder()
        .fluidInputs(fluid('bast_hree_concentrate') * 1000)
        .fluidInputs(fluid('sodium_chromate_solution') * 1000)
        .outputs(metaitem('dustBastHreeDoubleChromates'))
        .fluidOutputs(fluid('yttrium_chloride_solution') * 800)
        .duration(60)
        .EUt(60)
        .buildAndRegister()

BR.recipeBuilder()
        .inputs(ore('dustBastHreeDoubleChromates'))
        .fluidInputs(fluid('hydrochloric_acid') * 4000)
        .fluidOutputs(fluid('bast_yfree_hree_concentrate') * 1000)
        .fluidOutputs(fluid('hydrogen') * 2000)
        .duration(60)
        .EUt(60)
        .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
        .notConsumable(fluid('two_ethylhexanol') * 1000)
        .fluidInputs(fluid('bast_yfree_hree_concentrate') * 1000)
        .fluidInputs(fluid('sodium_hydroxide_solution') * 100)
        .fluidInputs(fluid('sodium_dodecyl_sulfate_solution') * 1000)
        .chancedOutput(metaitem('dustErbiumDodecylSulfate'), 5000, 0)
        .fluidOutputs(fluid('bast_erfree_hree_concentrate') * 1000)
        .duration(120)
        .EUt(120)
        .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
        .notConsumable(fluid('two_ethylhexanol') * 1000)
        .fluidInputs(fluid('bast_erfree_hree_concentrate') * 1000)
        .fluidInputs(fluid('sodium_hydroxide_solution') * 100)
        .fluidInputs(fluid('sodium_dodecyl_sulfate_solution') * 1000)
        .chancedOutput(metaitem('dustHolmiumDodecylSulfate'), 5000, 0)
        .fluidOutputs(fluid('bast_hofree_hree_concentrate') * 1000)
        .duration(120)
        .EUt(120)
        .buildAndRegister()

LCR.recipeBuilder()
        .fluidInputs(fluid('bast_hofree_hree_concentrate') * 1000)
        .fluidInputs(fluid('sodium_amalgam') * 400)
        .fluidOutputs(fluid('ytterbium_amalgam') * 400)
        .fluidOutputs(fluid('chlorine') * 1200)
        .fluidOutputs(fluid('bast_ybfree_hree_concentrate') * 1000)
        .duration(80)
        .EUt(480)
        .buildAndRegister()

ION_EXCHANGE.recipeBuilder()
        .inputs(metaitem('beads.rare_earth_cation_exchange') * 5)
        .fluidInputs(fluid('bast_ybfree_hree_concentrate') * 1000)
        .outputs(metaitem('beads.loaded_thulium_cation_exchange') * 5)
        .fluidOutputs(fluid('bast_tmfree_hree_concentrate') * 1000)
        .duration(400)
        .EUt(16)
        .buildAndRegister()

ION_EXCHANGE.recipeBuilder()
        .inputs(metaitem('beads.rare_earth_cation_exchange') * 8)
        .fluidInputs(fluid('bast_tmfree_hree_concentrate') * 1000)
        .outputs(metaitem('beads.loaded_lutetium_cation_exchange') * 8)
        .fluidOutputs(fluid('bast_hree_waste') * 1000)
        .duration(400)
        .EUt(16)
        .buildAndRegister()

// Monazite Element Extraction

MIXER.recipeBuilder()
        .fluidInputs(fluid('mona_cerium_extract') * 1000)
        .fluidInputs(fluid('diluted_hydrochloric_acid') * 10)
        .chancedOutput(metaitem('dustCeriumIvNitrate') * 17, 9100, 0)
        .fluidOutputs(fluid('tributyl_phosphate') * 1000)
        .duration(120)
        .EUt(30)
        .buildAndRegister()

FLUIDIZED_BED_REACTOR.recipeBuilder()
        .inputs(ore('dustAmmoniumCarbonate') * 14)
        .fluidInputs(fluid('mona_lree_concentrate') * 1000)
        .chancedOutput(metaitem('dustLanthanumCarbonate') * 14, 9580, 0)
        .fluidOutputs(fluid('mona_lafree_lree_concentrate') * 1000)
        .duration(40)
        .EUt(120)
        .buildAndRegister()

MIXER.recipeBuilder()
        .inputs(ore('dustSodiumHydroxide') * 3)
        .fluidInputs(fluid('mona_lafree_lree_concentrate') * 1000)
        .fluidOutputs(fluid('mona_lafree_lree_hydroxides') * 1000)
        .duration(80)
        .EUt(30)
        .buildAndRegister()

MIXER.recipeBuilder()
        .notConsumable(fluid('sodium_hydroxide') * 432)
        .inputs(ore('dustSodiumChlorate') * 5)
        .fluidInputs(fluid('mona_lafree_lree_hydroxides') * 1000)
        .fluidOutputs(fluid('mona_oxidised_lree_hydroxides') * 1000)
        .duration(80)
        .EUt(30)
        .buildAndRegister()

CENTRIFUGE.recipeBuilder()
        .fluidInputs(fluid('mona_oxidised_lree_hydroxides') * 1000)
        .chancedOutput(metaitem('dustPraseodymiumOxide') * 5, 7580, 0)
        .fluidOutputs(fluid('mona_prfree_lree_hydroxides') * 1000)
        .duration(120)
        .EUt(120)
        .buildAndRegister()

MIXER.recipeBuilder()
        .fluidInputs(fluid('distilled_water') * 1000)
        .fluidInputs(fluid('mona_prfree_lree_hydroxides') * 1000)
        .chancedOutput(metaitem('dustNeodymiumOxide') * 5, 8020, 0)
        .fluidOutputs(fluid('mona_lree_waste') * 1000)
        .duration(80)
        .EUt(16)
        .buildAndRegister()

BR.recipeBuilder()
        .inputs(ore('dustZinc'))
        .fluidInputs(fluid('mona_mree_concentrate') * 1000)
        .fluidInputs(fluid('sulfuric_acid') * 1514)
        .chancedOutput(metaitem('dustEuropiumIiSulfate') * 6, 5140, 0)
        .fluidOutputs(fluid('mona_eufree_mree_concentrate') * 1000)
        .duration(100)
        .EUt(120)
        .buildAndRegister()

LCR.recipeBuilder()
        .fluidInputs(fluid('mona_eufree_mree_concentrate') * 1000)
        .fluidInputs(fluid('sodium_amalgam') * 480)
        .fluidOutputs(fluid('samarium_amalgam') * 480)
        .fluidOutputs(fluid('chlorine') * 1440)
        .fluidOutputs(fluid('mona_smfree_mree_concentrate') * 1000)
        .duration(80)
        .EUt(480)
        .buildAndRegister()

ION_EXCHANGE.recipeBuilder()
        .inputs(metaitem('beads.strong_basic_anion_exchange') * 5)
        .fluidInputs(fluid('mona_smfree_mree_concentrate') * 1000)
        .outputs(metaitem('beads.loaded_gadolinium_anion_exchange') * 5)
        .fluidOutputs(fluid('mona_gdfree_mree_concentrate') * 1000)
        .duration(400)
        .EUt(16)
        .buildAndRegister()

ELECTROLYTIC_CELL.recipeBuilder()
        .inputs(ore('dustPotassiumCarbonate') * 6)
        .notConsumable(metaitem('stickPlatinum'))
        .notConsumable(fluid('potassium_hydroxide_solution') * 432)
        .fluidInputs(fluid('mona_gdfree_mree_concentrate') * 1000)
        .chancedOutput(metaitem('dustTerbiumCarbonate') * 14, 2158, 0)
        .fluidOutputs(fluid('mona_tbfree_mree_concentrate') * 1000)
        .duration(100)
        .EUt(1920)
        .buildAndRegister()

BR.recipeBuilder()
        .inputs(ore('dustSodiumFluoride') * 2)
        .fluidInputs(fluid('mona_tbfree_mree_concentrate') * 1000)
        .chancedOutput(metaitem('dustDysprosiumFluoride') * 4, 4260, 0)
        .fluidOutputs(fluid('mona_mree_waste') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()

BR.recipeBuilder()
        .fluidInputs(fluid('mona_hree_concentrate') * 1000)
        .fluidInputs(fluid('sodium_chromate_solution') * 1000)
        .outputs(metaitem('dustMonaHreeDoubleChromates'))
        .fluidOutputs(fluid('yttrium_chloride_solution') * 875)
        .duration(60)
        .EUt(60)
        .buildAndRegister()

BR.recipeBuilder()
        .inputs(ore('dustMonaHreeDoubleChromates'))
        .fluidInputs(fluid('hydrochloric_acid') * 4000)
        .fluidOutputs(fluid('mona_yfree_hree_concentrate') * 1000)
        .fluidOutputs(fluid('hydrogen') * 2000)
        .duration(60)
        .EUt(60)
        .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
        .notConsumable(fluid('two_ethylhexanol') * 1000)
        .fluidInputs(fluid('mona_yfree_hree_concentrate') * 1000)
        .fluidInputs(fluid('sodium_hydroxide_solution') * 100)
        .fluidInputs(fluid('sodium_dodecyl_sulfate_solution') * 1000)
        .chancedOutput(metaitem('dustErbiumDodecylSulfate'), 4350, 0)
        .fluidOutputs(fluid('mona_erfree_hree_concentrate') * 1000)
        .duration(120)
        .EUt(120)
        .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
        .notConsumable(fluid('two_ethylhexanol') * 1000)
        .fluidInputs(fluid('mona_erfree_hree_concentrate') * 1000)
        .fluidInputs(fluid('sodium_hydroxide_solution') * 100)
        .fluidInputs(fluid('sodium_dodecyl_sulfate_solution') * 1000)
        .chancedOutput(metaitem('dustHolmiumDodecylSulfate'), 4400, 0)
        .fluidOutputs(fluid('mona_hofree_hree_concentrate') * 1000)
        .duration(120)
        .EUt(120)
        .buildAndRegister()

LCR.recipeBuilder()
        .fluidInputs(fluid('mona_hofree_hree_concentrate') * 1000)
        .fluidInputs(fluid('sodium_amalgam') * 335)
        .fluidOutputs(fluid('ytterbium_amalgam') * 335)
        .fluidOutputs(fluid('chlorine') * 1005)
        .fluidOutputs(fluid('mona_ybfree_hree_concentrate') * 1000)
        .duration(80)
        .EUt(480)
        .buildAndRegister()

ION_EXCHANGE.recipeBuilder()
        .inputs(metaitem('beads.rare_earth_cation_exchange') * 3)
        .fluidInputs(fluid('mona_ybfree_hree_concentrate') * 1000)
        .outputs(metaitem('beads.loaded_thulium_cation_exchange') * 3)
        .fluidOutputs(fluid('mona_tmfree_hree_concentrate') * 1000)
        .duration(400)
        .EUt(16)
        .buildAndRegister()

ION_EXCHANGE.recipeBuilder()
        .inputs(metaitem('beads.rare_earth_cation_exchange') * 5)
        .fluidInputs(fluid('mona_tmfree_hree_concentrate') * 1000)
        .outputs(metaitem('beads.loaded_lutetium_cation_exchange') * 5)
        .fluidOutputs(fluid('mona_hree_waste') * 1000)
        .duration(400)
        .EUt(16)
        .buildAndRegister()

// Xenotime Element Extraction

MIXER.recipeBuilder()
        .fluidInputs(fluid('xeno_cerium_extract') * 1000)
        .fluidInputs(fluid('diluted_hydrochloric_acid') * 10)
        .chancedOutput(metaitem('dustCeriumIvNitrate') * 17, 6400, 0)
        .fluidOutputs(fluid('tributyl_phosphate') * 1000)
        .duration(120)
        .EUt(30)
        .buildAndRegister()

FLUIDIZED_BED_REACTOR.recipeBuilder()
        .inputs(ore('dustAmmoniumCarbonate') * 14)
        .fluidInputs(fluid('xeno_lree_concentrate') * 1000)
        .chancedOutput(metaitem('dustLanthanumCarbonate') * 14, 6000, 0)
        .fluidOutputs(fluid('xeno_lafree_lree_concentrate') * 1000)
        .duration(40)
        .EUt(120)
        .buildAndRegister()

MIXER.recipeBuilder()
        .inputs(ore('dustSodiumHydroxide') * 3)
        .fluidInputs(fluid('xeno_lafree_lree_concentrate') * 1000)
        .fluidOutputs(fluid('xeno_lafree_lree_hydroxides') * 1000)
        .duration(80)
        .EUt(30)
        .buildAndRegister()

MIXER.recipeBuilder()
        .notConsumable(fluid('sodium_hydroxide') * 432)
        .inputs(ore('dustSodiumChlorate') * 5)
        .fluidInputs(fluid('xeno_lafree_lree_hydroxides') * 1000)
        .fluidOutputs(fluid('xeno_oxidised_lree_hydroxides') * 1000)
        .duration(80)
        .EUt(30)
        .buildAndRegister()

CENTRIFUGE.recipeBuilder()
        .fluidInputs(fluid('xeno_oxidised_lree_hydroxides') * 1000)
        .chancedOutput(metaitem('dustPraseodymiumOxide') * 5, 2500, 0)
        .fluidOutputs(fluid('xeno_prfree_lree_hydroxides') * 1000)
        .duration(120)
        .EUt(120)
        .buildAndRegister()

MIXER.recipeBuilder()
        .fluidInputs(fluid('distilled_water') * 1000)
        .fluidInputs(fluid('xeno_prfree_lree_hydroxides') * 1000)
        .chancedOutput(metaitem('dustNeodymiumOxide') * 5, 5000, 0)
        .fluidOutputs(fluid('xeno_lree_waste'))
        .duration(80)
        .EUt(16)
        .buildAndRegister()

BR.recipeBuilder()
        .inputs(ore('dustZinc'))
        .fluidInputs(fluid('xeno_mree_concentrate') * 1000)
        .fluidInputs(fluid('sulfuric_acid') * 1800)
        .chancedOutput(metaitem('dustEuropiumIiSulfate') * 6, 8000, 0)
        .fluidOutputs(fluid('xeno_eufree_mree_concentrate') * 1000)
        .duration(100)
        .EUt(120)
        .buildAndRegister()

LCR.recipeBuilder()
        .fluidInputs(fluid('xeno_eufree_mree_concentrate') * 1000)
        .fluidInputs(fluid('sodium_amalgam') * 800)
        .fluidOutputs(fluid('samarium_amalgam') * 800)
        .fluidOutputs(fluid('chlorine') * 2400)
        .fluidOutputs(fluid('xeno_smfree_mree_concentrate') * 1000)
        .duration(80)
        .EUt(480)
        .buildAndRegister()

ION_EXCHANGE.recipeBuilder()
        .inputs(metaitem('beads.strong_basic_anion_exchange') * 8)
        .fluidInputs(fluid('xeno_smfree_mree_concentrate') * 1000)
        .outputs(metaitem('beads.loaded_gadolinium_anion_exchange') * 8)
        .fluidOutputs(fluid('xeno_gdfree_mree_concentrate') * 1000)
        .duration(400)
        .EUt(16)
        .buildAndRegister()

ELECTROLYTIC_CELL.recipeBuilder()
        .inputs(ore('dustPotassiumCarbonate') * 6)
        .notConsumable(metaitem('stickPlatinum'))
        .notConsumable(fluid('potassium_hydroxide_solution') * 432)
        .fluidInputs(fluid('xeno_gdfree_mree_concentrate') * 1000)
        .chancedOutput(metaitem('dustTerbiumCarbonate') * 14, 3500, 0)
        .fluidOutputs(fluid('xeno_tbfree_mree_concentrate') * 1000)
        .duration(100)
        .EUt(1920)
        .buildAndRegister()

BR.recipeBuilder()
        .inputs(ore('dustSodiumFluoride') * 2)
        .fluidInputs(fluid('xeno_tbfree_mree_concentrate') * 1000)
        .chancedOutput(metaitem('dustDysprosiumFluoride') * 4, 7200, 0)
        .fluidOutputs(fluid('xeno_mree_waste') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()

BR.recipeBuilder()
        .fluidInputs(fluid('xeno_hree_concentrate') * 1000)
        .fluidInputs(fluid('sodium_chromate_solution') * 1000)
        .outputs(metaitem('dustXenoHreeDoubleChromates'))
        .fluidOutputs(fluid('yttrium_chloride_solution') * 800)
        .duration(60)
        .EUt(60)
        .buildAndRegister()

BR.recipeBuilder()
        .inputs(ore('dustXenoHreeDoubleChromates'))
        .fluidInputs(fluid('hydrochloric_acid') * 800)
        .fluidOutputs(fluid('xeno_yfree_hree_concentrate') * 200)
        .fluidOutputs(fluid('hydrogen') * 400)
        .duration(60)
        .EUt(60)
        .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
        .notConsumable(fluid('two_ethylhexanol') * 1000)
        .fluidInputs(fluid('xeno_yfree_hree_concentrate') * 1000)
        .fluidInputs(fluid('sodium_hydroxide_solution') * 100)
        .fluidInputs(fluid('sodium_dodecyl_sulfate_solution') * 1000)
        .chancedOutput(metaitem('dustErbiumDodecylSulfate'), 8000, 0)
        .fluidOutputs(fluid('xeno_erfree_hree_concentrate') * 1000)
        .duration(120)
        .EUt(120)
        .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
        .notConsumable(fluid('two_ethylhexanol') * 1000)
        .fluidInputs(fluid('xeno_erfree_hree_concentrate') * 1000)
        .fluidInputs(fluid('sodium_hydroxide_solution') * 100)
        .fluidInputs(fluid('sodium_dodecyl_sulfate_solution') * 1000)
        .chancedOutput(metaitem('dustHolmiumDodecylSulfate'), 7000, 0)
        .fluidOutputs(fluid('xeno_hofree_hree_concentrate') * 1000)
        .duration(120)
        .EUt(120)
        .buildAndRegister()

LCR.recipeBuilder()
        .fluidInputs(fluid('xeno_hofree_hree_concentrate') * 1000)
        .fluidInputs(fluid('sodium_amalgam') * 600)
        .fluidOutputs(fluid('ytterbium_amalgam') * 600)
        .fluidOutputs(fluid('chlorine') * 1800)
        .fluidOutputs(fluid('xeno_ybfree_hree_concentrate') * 1000)
        .duration(80)
        .EUt(480)
        .buildAndRegister()

ION_EXCHANGE.recipeBuilder()
        .inputs(metaitem('beads.rare_earth_cation_exchange') * 7)
        .fluidInputs(fluid('xeno_ybfree_hree_concentrate') * 1000)
        .outputs(metaitem('beads.loaded_thulium_cation_exchange') * 7)
        .fluidOutputs(fluid('xeno_tmfree_hree_concentrate') * 1000)
        .duration(400)
        .EUt(16)
        .buildAndRegister()

ION_EXCHANGE.recipeBuilder()
        .inputs(metaitem('beads.rare_earth_cation_exchange') * 7)
        .fluidInputs(fluid('xeno_tmfree_hree_concentrate') * 1000)
        .outputs(metaitem('beads.loaded_lutetium_cation_exchange') * 7)
        .fluidOutputs(fluid('xeno_hree_waste') * 1000)
        .duration(400)
        .EUt(16)
        .buildAndRegister()