import globals.Globals
import static globals.SinteringGlobals.*

import static gregtech.api.unification.material.Materials.*;
import gregtech.api.unification.material.MarkerMaterials;
import static gregtech.api.unification.ore.OrePrefix.dye;

GRAVITY_SEPARATOR = recipemap('gravity_separator')
MIXER = recipemap('mixer')
FROTH_FLOTATION = recipemap('froth_flotation')
CLARIFIER = recipemap('clarifier')
ROASTER = recipemap('roaster')
ROTARY_KILN = recipemap('rotary_kiln')
BR = recipemap('batch_reactor')
BLENDER = recipemap('blender')
FLUIDIZED_BED_REACTOR = recipemap('fluidized_bed_reactor')
ION_EXCHANGE = recipemap('ion_exchange_column')
CENTRIFUGE = recipemap('centrifuge')
LCR = recipemap('large_chemical_reactor')
ELECTROLYTIC_CELL = recipemap('electrolytic_cell')
SIFTER = recipemap('sifter')
VACUUM_CHAMBER = recipemap('vacuum_chamber')

// Bastnasite Pre-processing
mods.gregtech.macerator.recipeBuilder()
        .inputs(item('susy:resource_block', 7))
        .outputs(metaitem('dustBastnasite') * 8)
        .duration(240)
        .EUt(7)
        .buildAndRegister();

GRAVITY_SEPARATOR.recipeBuilder()
        .inputs(ore('dustBastnasite'))
        .outputs(metaitem('dustSiftedBastnasite'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

MIXER.recipeBuilder()
        .inputs(ore('dustSiftedBastnasite'))
        .fluidInputs(fluid('distilled_water') * 1000)
        .fluidOutputs(fluid('impure_bastnasite_slurry'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
        .notConsumable(fluid('methyl_isobutyl_carbinol'))
        .notConsumable(fluid('oleic_acid'))
        .fluidInputs(fluid('impure_bastnasite_slurry'))
        .fluidOutputs(fluid('bastnasite_slurry'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

CLARIFIER.recipeBuilder()
        .fluidInputs(fluid('bastnasite_slurry'))
        .outputs(metaitem('dustFlotatedBastnasite'))
        .fluidOutputs(fluid('wastewater'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

ROASTER.recipeBuilder()
        .inputs(ore('dustFlotatedBastnasite'))
        .fluidInputs(fluid('sulfuric_acid'))
        .fluidOutputs(fluid('hydrogen_fluoride'))
        .fluidOutputs(fluid('roasted_bastnasite_leach'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


for (fuel in sintering_fuels) {
    if (!fuel.isPlasma) {
        ROTARY_KILN.recipeBuilder()
                .inputs(ore('dustSodaAsh') * 24)
                .fluidInputs(fluid(fuel.name) * fuel.amountRequired)
                .fluidInputs(fluid('oxygen') * 50)
                .fluidInputs(fluid('roasted_bastnasite_leach'))
                .outputs(metaitem('dustConcentratedBastnasite'))
                .fluidOutputs(fluid('carbon_dioxide'))
                .duration(400)
                .EUt(Globals.voltAmps[2])
                .buildAndRegister()
    }
}

BR.recipeBuilder()
        .inputs(ore('dustConcentratedBastnasite'))
        .fluidInputs(fluid('sodium_hydroxide_solution'))
        .outputs(metaitem('dustBastReHydroxides'))
        .fluidOutputs(fluid('sodium_sulfate_solution'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

// Monazite Pre-processing

MIXER.recipeBuilder()
        .inputs(ore('dustMonazite'))
        .fluidInputs(fluid('sulfuric_acid'))
        .fluidOutputs(fluid('monazite_leach'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

SIFTER.recipeBuilder()
        .notConsumable(metaitem('item_filter'))
        .fluidInputs(fluid('monazite_leach'))
        .chancedOutput(metaitem('dustIlmenite'), 1500, 0)
        .chancedOutput(metaitem('dustZircon'), 500, 0)
        .chancedOutput(metaitem('dustQuartzite'), 1000, 0)
        .fluidOutputs(fluid('sifted_monazite_leach'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

CENTRIFUGE.recipeBuilder()
        .fluidInputs(fluid('sifted_monazite_leach'))
        .fluidInputs(fluid('ammonia_solution'))
        .outputs(metaitem('dustThoriumHydroxidePrecipitate'))
        .fluidOutputs(fluid('thfree_monazite_leach'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

CENTRIFUGE.recipeBuilder()
        .fluidInputs(fluid('thfree_monazite_leach'))
        .fluidInputs(fluid('ammonia_solution'))
        .outputs(metaitem('dustMonaReHydroxides'))
        .fluidOutputs(fluid('refree_monazite_leach'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

CENTRIFUGE.recipeBuilder()
        .fluidInputs(fluid('refree_monazite_leach'))
        .fluidInputs(fluid('ammonia_solution'))
        .outputs(metaitem('dustUranylHydroxidePrecipitate'))
        .fluidOutputs(fluid('monazite_waste'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

// Xenotime Pre-processing

for (fuel in sintering_fuels) {
    if (!fuel.isPlasma) {
        ROTARY_KILN.recipeBuilder()
                .inputs(ore('dustSodaAsh') * 24)
                .inputs(ore('dustXenotime'))
                .fluidInputs(fluid(fuel.name) * fuel.amountRequired)
                .fluidInputs(fluid('oxygen') * 50)
                .outputs(metaitem('dustRoastedXenotime'))
                .fluidOutputs(fluid('carbon_dioxide'))
                .duration(400)
                .EUt(Globals.voltAmps[2])
                .buildAndRegister()
    }
}

MIXER.recipeBuilder()
        .inputs(ore('dustRoastedXenotime'))
        .fluidInputs(fluid('distilled_water') * 4000)
        .fluidOutputs(fluid('xenotime_slurry') * 4000)
        .duration(100)
        .EUt(30)
        .buildAndRegister()

VACUUM_CHAMBER.recipeBuilder()
        .notConsumable(metaitem('item_filter'))
        .fluidInputs(fluid('xenotime_slurry') * 4000)
        .outputs(metaitem('dustXenotimeResidue'))
        .fluidOutputs(fluid('xenotime_phosphate_waste') * 4000)
        .duration(160)
        .EUt(80)
        .buildAndRegister()

MIXER.recipeBuilder()
        .inputs(ore('dustXenotimeResidue'))
        .fluidInputs(fluid('nitric_acid') * 1000)
        .fluidOutputs(fluid('crude_xenotime_nitrate_solution') * 1000)
        .duration(80)
        .EUt(120)
        .buildAndRegister()

VACUUM_CHAMBER.recipeBuilder()
        .notConsumable(metaitem('item_filter'))
        .fluidInputs(fluid('crude_xenotime_nitrate_solution') * 1000)
        .chancedOutput(metaitem('dustXenotimeTailing'), 1000, 0)
        .fluidOutputs(fluid('xeno_re_nitrates_solution') * 1000)
        .duration(100)
        .EUt(80)
        .buildAndRegister()

SIFTER.recipeBuilder()
        .inputs(ore('dustXenotimeTailing'))
        .chancedOutput(metaitem('dustCassiterite') * 3, 500, 0)
        .duration(100)
        .EUt(30)
        .buildAndRegister()

// Bastnasite Concentrate Processing

MIXER.recipeBuilder()
        .inputs(ore('dustBastReHydroxides'))
        .fluidInputs(fluid('nitric_acid'))
        .fluidOutputs(fluid('bast_re_nitrates_solution'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

MIXER.recipeBuilder()
        .inputs(ore('dustPotassiumPermanganate'))
        .fluidInputs(fluid('nitric_acid'))
        .fluidInputs(fluid('bast_re_nitrates_solution'))
        .fluidOutputs(fluid('bast_ox_re_nitrates_solution'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

BLENDER.recipeBuilder()
        .fluidInputs(fluid('bast_ox_re_nitrates_solution'))
        .fluidInputs(fluid('tributyl_phosphate'))
        .fluidOutputs(fluid('bast_cerium_extract'))
        .fluidOutputs(fluid('bast_cefree_re_nitrates_solution'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

BLENDER.recipeBuilder()
        .fluidInputs(fluid('bast_cefree_re_nitrates_solution'))
        .fluidInputs(fluid('rare_earth_extraction_mixture'))
        .fluidOutputs(fluid('bast_lree_concentrate'))
        .fluidOutputs(fluid('bast_dehpa_extract'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

MIXER.recipeBuilder()
        .fluidInputs(fluid('hydrochloric_acid'))
        .fluidInputs(fluid('bast_dehpa_extract'))
        .fluidOutputs(fluid('rare_earth_extraction_mixture'))
        .fluidOutputs(fluid('bast_re_chlorides_solution'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

BLENDER.recipeBuilder()
        .fluidInputs(fluid('bast_re_chlorides_solution'))
        .fluidInputs(fluid('rare_earth_separation_mixture'))
        .fluidOutputs(fluid('bast_mree_concentrate'))
        .fluidOutputs(fluid('bast_ehehpa_extract'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

MIXER.recipeBuilder()
        .fluidInputs(fluid('hydrochloric_acid'))
        .fluidInputs(fluid('bast_ehehpa_extract'))
        .fluidOutputs(fluid('rare_earth_separation_mixture'))
        .fluidOutputs(fluid('bast_hree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

// Monazite Concentrate Processing

MIXER.recipeBuilder()
        .inputs(ore('dustMonaReHydroxides'))
        .fluidInputs(fluid('nitric_acid'))
        .fluidOutputs(fluid('mona_re_nitrates_solution'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


MIXER.recipeBuilder()
        .inputs(ore('dustPotassiumPermanganate'))
        .fluidInputs(fluid('nitric_acid'))
        .fluidInputs(fluid('mona_re_nitrates_solution'))
        .fluidOutputs(fluid('mona_ox_re_nitrates_solution'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


BLENDER.recipeBuilder()
        .fluidInputs(fluid('mona_ox_re_nitrates_solution'))
        .fluidInputs(fluid('tributyl_phosphate'))
        .fluidOutputs(fluid('mona_cerium_extract'))
        .fluidOutputs(fluid('mona_cefree_re_nitrates_solution'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


BLENDER.recipeBuilder()
        .fluidInputs(fluid('mona_cefree_re_nitrates_solution'))
        .fluidInputs(fluid('rare_earth_extraction_mixture'))
        .fluidOutputs(fluid('mona_lree_concentrate'))
        .fluidOutputs(fluid('mona_dehpa_extract'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


MIXER.recipeBuilder()
        .fluidInputs(fluid('hydrochloric_acid'))
        .fluidInputs(fluid('mona_dehpa_extract'))
        .fluidOutputs(fluid('rare_earth_extraction_mixture'))
        .fluidOutputs(fluid('mona_re_chlorides_solution'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


BLENDER.recipeBuilder()
        .fluidInputs(fluid('mona_re_chlorides_solution'))
        .fluidInputs(fluid('rare_earth_separation_mixture'))
        .fluidOutputs(fluid('mona_mree_concentrate'))
        .fluidOutputs(fluid('mona_ehehpa_extract'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


MIXER.recipeBuilder()
        .fluidInputs(fluid('hydrochloric_acid'))
        .fluidInputs(fluid('mona_ehehpa_extract'))
        .fluidOutputs(fluid('rare_earth_separation_mixture'))
        .fluidOutputs(fluid('mona_hree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

// Xenotime Concentrate Processing

MIXER.recipeBuilder()
        .inputs(ore('dustPotassiumPermanganate'))
        .fluidInputs(fluid('nitric_acid'))
        .fluidInputs(fluid('xeno_re_nitrates_solution'))
        .fluidOutputs(fluid('xeno_ox_re_nitrates_solution'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


BLENDER.recipeBuilder()
        .fluidInputs(fluid('xeno_ox_re_nitrates_solution'))
        .fluidInputs(fluid('tributyl_phosphate'))
        .fluidOutputs(fluid('xeno_cerium_extract'))
        .fluidOutputs(fluid('xeno_cefree_re_nitrates_solution'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


BLENDER.recipeBuilder()
        .fluidInputs(fluid('xeno_cefree_re_nitrates_solution'))
        .fluidInputs(fluid('rare_earth_extraction_mixture'))
        .fluidOutputs(fluid('xeno_lree_concentrate'))
        .fluidOutputs(fluid('xeno_dehpa_extract'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


MIXER.recipeBuilder()
        .fluidInputs(fluid('hydrochloric_acid'))
        .fluidInputs(fluid('xeno_dehpa_extract'))
        .fluidOutputs(fluid('rare_earth_extraction_mixture'))
        .fluidOutputs(fluid('xeno_re_chlorides_solution'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


BLENDER.recipeBuilder()
        .fluidInputs(fluid('xeno_re_chlorides_solution'))
        .fluidInputs(fluid('rare_earth_separation_mixture'))
        .fluidOutputs(fluid('xeno_mree_concentrate'))
        .fluidOutputs(fluid('xeno_ehehpa_extract'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


MIXER.recipeBuilder()
        .fluidInputs(fluid('hydrochloric_acid'))
        .fluidInputs(fluid('xeno_ehehpa_extract'))
        .fluidOutputs(fluid('rare_earth_separation_mixture'))
        .fluidOutputs(fluid('xeno_hree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


// Bastnasite Element Extraction

MIXER.recipeBuilder()
        .fluidInputs(fluid('bast_cerium_extract'))
        .fluidInputs(fluid('diluted_hydrochloric_acid'))
        .outputs(metaitem('dustCeriumIvNitrate'))
        .fluidOutputs(fluid('tributyl_phosphate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

FLUIDIZED_BED_REACTOR.recipeBuilder()
        .inputs(ore('dustAmmoniumCarbonate'))
        .fluidInputs(fluid('bast_lree_concentrate'))
        .chancedOutput(metaitem('dustLanthanumCarbonate'), 1500, 0)
        .fluidOutputs(fluid('bast_lafree_lree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

MIXER.recipeBuilder()
        .inputs(ore('dustSodiumHydroxide'))
        .fluidInputs(fluid('bast_lafree_lree_concentrate'))
        .fluidOutputs(fluid('bast_lafree_lree_hydroxides'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

MIXER.recipeBuilder()
        .inputs(ore('dustPotassiumChlorate'))
        .fluidInputs(fluid('potassium_hydroxide'))
        .fluidInputs(fluid('bast_lafree_lree_hydroxides'))
        .fluidOutputs(fluid('bast_oxidised_lree_hydroxides'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

CENTRIFUGE.recipeBuilder()
        .fluidInputs(fluid('bast_oxidised_lree_hydroxides'))
        .chancedOutput(metaitem('dustPraseodymiumOxide'), 1500, 0)
        .fluidOutputs(fluid('bast_prfree_lree_hydroxides'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

MIXER.recipeBuilder()
        .fluidInputs(fluid('distilled_water'))
        .fluidInputs(fluid('bast_prfree_lree_hydroxides'))
        .chancedOutput(metaitem('dustNeodymiumOxide'), 1500, 0)
        .fluidOutputs(fluid('bast_lree_waste'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

BR.recipeBuilder()
        .inputs(ore('dustZinc'))
        .fluidInputs(fluid('bast_mree_concentrate'))
        .fluidInputs(fluid('sulfuric_acid'))
        .chancedOutput(metaitem('dustEuropiumIiSulfate'), 1500, 0)
        .fluidOutputs(fluid('bast_eufree_mree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

LCR.recipeBuilder()
        .fluidInputs(fluid('bast_eufree_mree_concentrate'))
        .fluidInputs(fluid('sodium_amalgam'))
        .fluidOutputs(fluid('samarium_amalgam'))
        .fluidOutputs(fluid('chlorine'))
        .fluidOutputs(fluid('bast_smfree_mree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

ION_EXCHANGE.recipeBuilder()
        .inputs(metaitem('beads.strong_basic_anion_exchange'))
        .fluidInputs(fluid('bast_smfree_mree_concentrate'))
        .outputs(metaitem('beads.loaded_gadolinium_anion_exchange'))
        .fluidOutputs(fluid('bast_gdfree_mree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

ELECTROLYTIC_CELL.recipeBuilder()
        .inputs(ore('dustPotassiumCarbonate'))
        .notConsumable(metaitem('stickPlatinum'))
        .notConsumable(fluid('potassium_hydroxide_solution'))
        .fluidInputs(fluid('bast_gdfree_mree_concentrate'))
        .chancedOutput(metaitem('dustTerbiumCarbonate'), 1500, 0)
        .fluidOutputs(fluid('bast_tbfree_mree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

BR.recipeBuilder()
        .inputs(ore('dustSodiumFluoride'))
        .fluidInputs(fluid('bast_tbfree_mree_concentrate'))
        .chancedOutput(metaitem('dustDysprosiumFluoride'),1500, 0)
        .fluidOutputs(fluid('bast_mree_waste'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

BR.recipeBuilder()
        .fluidInputs(fluid('bast_hree_concentrate'))
        .fluidInputs(fluid('sodium_chromate_solution'))
        .outputs(metaitem('dustBastHreeDoubleChromates'))
        .fluidOutputs(fluid('yttrium_chloride_solution'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

BR.recipeBuilder()
        .inputs(ore('dustBastHreeDoubleChromates'))
        .inputs(ore('potassium_chloride'))
        .fluidInputs(fluid('hydrochloric_acid'))
        .fluidOutputs(fluid('bast_yfree_hree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
        .notConsumable(fluid('two_ethylhexanol'))
        .fluidInputs(fluid('bast_yfree_hree_concentrate'))
        .fluidInputs(fluid('sodium_hydroxide_solution'))
        .fluidInputs(fluid('sodium_dodecyl_sulfate_solution'))
        .chancedOutput(metaitem('dustErbiumDodecylSulfate'), 1500, 0)
        .fluidOutputs(fluid('bast_erfree_hree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

FROTH_FLOTATION.recipeBuilder()
        .notConsumable(fluid('two_ethylhexanol'))
        .fluidInputs(fluid('bast_erfree_hree_concentrate'))
        .fluidInputs(fluid('sodium_hydroxide_solution'))
        .fluidInputs(fluid('sodium_dodecyl_sulfate_solution'))
        .chancedOutput(metaitem('dustHolmiumDodecylSulfate'), 1500, 0)
        .fluidOutputs(fluid('bast_hofree_hree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

LCR.recipeBuilder()
        .fluidInputs(fluid('bast_hofree_hree_concentrate'))
        .fluidInputs(fluid('sodium_amalgam'))
        .fluidOutputs(fluid('ytterbium_amalgam'))
        .fluidOutputs(fluid('bast_ybfree_hree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

ION_EXCHANGE.recipeBuilder()
        .inputs(metaitem('beads.rare_earth_cation_exchange'))
        .fluidInputs(fluid('bast_ybfree_hree_concentrate'))
        .outputs(metaitem('beads.loaded_thulium_cation_exchange'))
        .fluidOutputs(fluid('bast_tmfree_hree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

ION_EXCHANGE.recipeBuilder()///////f
        .inputs(metaitem('beads.rare_earth_cation_exchange'))
        .fluidInputs(fluid('bast_tmfree_hree_concentrate'))
        .outputs(metaitem('beads.loaded_lutetium_cation_exchange'))
        .fluidOutputs(fluid('bast_hree_waste'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

// Monazite Element Extraction

MIXER.recipeBuilder()
        .fluidInputs(fluid('mona_cerium_extract'))
        .fluidInputs(fluid('diluted_hydrochloric_acid'))
        .outputs(metaitem('dustCeriumIvNitrate'))
        .fluidOutputs(fluid('tributyl_phosphate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


FLUIDIZED_BED_REACTOR.recipeBuilder()
        .inputs(ore('dustAmmoniumCarbonate'))
        .fluidInputs(fluid('mona_lree_concentrate'))
        .outputs(metaitem('dustLanthanumCarbonate'))
        .fluidOutputs(fluid('mona_lafree_lree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


MIXER.recipeBuilder()
        .inputs(ore('dustSodiumHydroxide'))
        .fluidInputs(fluid('mona_lafree_lree_concentrate'))
        .fluidOutputs(fluid('mona_lafree_lree_hydroxides'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


MIXER.recipeBuilder()
        .inputs(ore('dustPotassiumChlorate'))
        .fluidInputs(fluid('potassium_hydroxide'))
        .fluidInputs(fluid('mona_lafree_lree_hydroxides'))
        .fluidOutputs(fluid('mona_oxidised_lree_hydroxides'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


CENTRIFUGE.recipeBuilder()
        .fluidInputs(fluid('mona_oxidised_lree_hydroxides'))
        .outputs(metaitem('dustPraseodymiumOxide'))
        .fluidOutputs(fluid('mona_prfree_lree_hydroxides'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


MIXER.recipeBuilder()
        .fluidInputs(fluid('distilled_water'))
        .fluidInputs(fluid('mona_prfree_lree_hydroxides'))
        .outputs(metaitem('dustNeodymiumOxide'))
        .fluidOutputs(fluid('mona_lree_waste'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


BR.recipeBuilder()
        .inputs(ore('dustZinc'))
        .fluidInputs(fluid('mona_mree_concentrate'))
        .fluidInputs(fluid('sulfuric_acid'))
        .outputs(metaitem('dustEuropiumIiSulfate'))
        .fluidOutputs(fluid('mona_eufree_mree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


LCR.recipeBuilder()
        .fluidInputs(fluid('mona_eufree_mree_concentrate'))
        .fluidInputs(fluid('sodium_amalgam'))
        .fluidOutputs(fluid('samarium_amalgam'))
        .fluidOutputs(fluid('chlorine'))
        .fluidOutputs(fluid('mona_smfree_mree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


ION_EXCHANGE.recipeBuilder()
        .inputs(metaitem('beads.strong_basic_anion_exchange'))
        .fluidInputs(fluid('mona_smfree_mree_concentrate'))
        .outputs(metaitem('beads.loaded_gadolinium_anion_exchange'))
        .fluidOutputs(fluid('mona_gdfree_mree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


ELECTROLYTIC_CELL.recipeBuilder()
        .inputs(ore('dustPotassiumCarbonate'))
        .notConsumable(metaitem('stickPlatinum'))
        .notConsumable(fluid('potassium_hydroxide_solution'))
        .fluidInputs(fluid('mona_gdfree_mree_concentrate'))
        .outputs(metaitem('dustTerbiumCarbonate'))
        .fluidOutputs(fluid('mona_tbfree_mree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


BR.recipeBuilder()
        .inputs(ore('dustSodiumFluoride'))
        .fluidInputs(fluid('mona_tbfree_mree_concentrate'))
        .outputs(metaitem('dustDysprosiumFluoride'))
        .fluidOutputs(fluid('mona_mree_waste'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


BR.recipeBuilder()
        .fluidInputs(fluid('mona_hree_concentrate'))
        .fluidInputs(fluid('sodium_chromate_solution'))
        .outputs(metaitem('dustMonaHreeDoubleChromates'))
        .fluidOutputs(fluid('yttrium_chloride_solution'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


BR.recipeBuilder()
        .inputs(ore('dustMonaHreeDoubleChromates'))
        .inputs(ore('potassium_chloride'))
        .fluidInputs(fluid('hydrochloric_acid'))
        .fluidOutputs(fluid('mona_yfree_hree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


FROTH_FLOTATION.recipeBuilder()
        .notConsumable(fluid('two_ethylhexanol'))
        .fluidInputs(fluid('mona_yfree_hree_concentrate'))
        .fluidInputs(fluid('sodium_hydroxide_solution'))
        .fluidInputs(fluid('sodium_dodecyl_sulfate_solution'))
        .outputs(metaitem('dustErbiumDodecylSulfate'))
        .fluidOutputs(fluid('mona_erfree_hree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


FROTH_FLOTATION.recipeBuilder()
        .notConsumable(fluid('two_ethylhexanol'))
        .fluidInputs(fluid('mona_erfree_hree_concentrate'))
        .fluidInputs(fluid('sodium_hydroxide_solution'))
        .fluidInputs(fluid('sodium_dodecyl_sulfate_solution'))
        .outputs(metaitem('dustHolmiumDodecylSulfate'))
        .fluidOutputs(fluid('mona_hofree_hree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


LCR.recipeBuilder()
        .fluidInputs(fluid('mona_hofree_hree_concentrate'))
        .fluidInputs(fluid('sodium_amalgam'))
        .fluidOutputs(fluid('ytterbium_amalgam'))
        .fluidOutputs(fluid('mona_ybfree_hree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


ION_EXCHANGE.recipeBuilder()
        .inputs(metaitem('beads.rare_earth_cation_exchange'))
        .fluidInputs(fluid('mona_ybfree_hree_concentrate'))
        .outputs(metaitem('beads.loaded_thulium_cation_exchange'))
        .fluidOutputs(fluid('mona_tmfree_hree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


ION_EXCHANGE.recipeBuilder()
        .inputs(metaitem('beads.rare_earth_cation_exchange'))
        .fluidInputs(fluid('mona_tmfree_hree_concentrate'))
        .outputs(metaitem('beads.loaded_lutetium_cation_exchange'))
        .fluidOutputs(fluid('mona_hree_waste'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()

// Xenotime Element Extraction

MIXER.recipeBuilder()
        .fluidInputs(fluid('xeno_cerium_extract'))
        .fluidInputs(fluid('diluted_hydrochloric_acid'))
        .outputs(metaitem('dustCeriumIvNitrate'))
        .fluidOutputs(fluid('tributyl_phosphate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


FLUIDIZED_BED_REACTOR.recipeBuilder()
        .inputs(ore('dustAmmoniumCarbonate'))
        .fluidInputs(fluid('xeno_lree_concentrate'))
        .outputs(metaitem('dustLanthanumCarbonate'))
        .fluidOutputs(fluid('xeno_lafree_lree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


MIXER.recipeBuilder()
        .inputs(ore('dustSodiumHydroxide'))
        .fluidInputs(fluid('xeno_lafree_lree_concentrate'))
        .fluidOutputs(fluid('xeno_lafree_lree_hydroxides'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


MIXER.recipeBuilder()
        .inputs(ore('dustPotassiumChlorate'))
        .fluidInputs(fluid('potassium_hydroxide'))
        .fluidInputs(fluid('xeno_lafree_lree_hydroxides'))
        .fluidOutputs(fluid('xeno_oxidised_lree_hydroxides'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


CENTRIFUGE.recipeBuilder()
        .fluidInputs(fluid('xeno_oxidised_lree_hydroxides'))
        .outputs(metaitem('dustPraseodymiumOxide'))
        .fluidOutputs(fluid('xeno_prfree_lree_hydroxides'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


MIXER.recipeBuilder()
        .fluidInputs(fluid('distilled_water'))
        .fluidInputs(fluid('xeno_prfree_lree_hydroxides'))
        .outputs(metaitem('dustNeodymiumOxide'))
        .fluidOutputs(fluid('xeno_lree_waste'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


BR.recipeBuilder()
        .inputs(ore('dustZinc'))
        .fluidInputs(fluid('xeno_mree_concentrate'))
        .fluidInputs(fluid('sulfuric_acid'))
        .outputs(metaitem('dustEuropiumIiSulfate'))
        .fluidOutputs(fluid('xeno_eufree_mree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


LCR.recipeBuilder()
        .fluidInputs(fluid('xeno_eufree_mree_concentrate'))
        .fluidInputs(fluid('sodium_amalgam'))
        .fluidOutputs(fluid('samarium_amalgam'))
        .fluidOutputs(fluid('chlorine'))
        .fluidOutputs(fluid('xeno_smfree_mree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


ION_EXCHANGE.recipeBuilder()
        .inputs(metaitem('beads.strong_basic_anion_exchange'))
        .fluidInputs(fluid('xeno_smfree_mree_concentrate'))
        .outputs(metaitem('beads.loaded_gadolinium_anion_exchange'))
        .fluidOutputs(fluid('xeno_gdfree_mree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


ELECTROLYTIC_CELL.recipeBuilder()
        .inputs(ore('dustPotassiumCarbonate'))
        .notConsumable(metaitem('stickPlatinum'))
        .notConsumable(fluid('potassium_hydroxide_solution'))
        .fluidInputs(fluid('xeno_gdfree_mree_concentrate'))
        .outputs(metaitem('dustTerbiumCarbonate'))
        .fluidOutputs(fluid('xeno_tbfree_mree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


BR.recipeBuilder()
        .inputs(ore('dustSodiumFluoride'))
        .fluidInputs(fluid('xeno_tbfree_mree_concentrate'))
        .outputs(metaitem('dustDysprosiumFluoride'))
        .fluidOutputs(fluid('xeno_mree_waste'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


BR.recipeBuilder()
        .fluidInputs(fluid('xeno_hree_concentrate'))
        .fluidInputs(fluid('sodium_chromate_solution'))
        .outputs(metaitem('dustXenoHreeDoubleChromates'))
        .fluidOutputs(fluid('yttrium_chloride_solution'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


BR.recipeBuilder()
        .inputs(ore('dustXenoHreeDoubleChromates'))
        .inputs(ore('potassium_chloride'))
        .fluidInputs(fluid('hydrochloric_acid'))
        .fluidOutputs(fluid('xeno_yfree_hree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


FROTH_FLOTATION.recipeBuilder()
        .notConsumable(fluid('two_ethylhexanol'))
        .fluidInputs(fluid('xeno_yfree_hree_concentrate'))
        .fluidInputs(fluid('sodium_hydroxide_solution'))
        .fluidInputs(fluid('sodium_dodecyl_sulfate_solution'))
        .outputs(metaitem('dustErbiumDodecylSulfate'))
        .fluidOutputs(fluid('xeno_erfree_hree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


FROTH_FLOTATION.recipeBuilder()
        .notConsumable(fluid('two_ethylhexanol'))
        .fluidInputs(fluid('xeno_erfree_hree_concentrate'))
        .fluidInputs(fluid('sodium_hydroxide_solution'))
        .fluidInputs(fluid('sodium_dodecyl_sulfate_solution'))
        .outputs(metaitem('dustHolmiumDodecylSulfate'))
        .fluidOutputs(fluid('xeno_hofree_hree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


LCR.recipeBuilder()
        .fluidInputs(fluid('xeno_hofree_hree_concentrate'))
        .fluidInputs(fluid('sodium_amalgam'))
        .fluidOutputs(fluid('ytterbium_amalgam'))
        .fluidOutputs(fluid('xeno_ybfree_hree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


ION_EXCHANGE.recipeBuilder()
        .inputs(metaitem('beads.rare_earth_cation_exchange'))
        .fluidInputs(fluid('xeno_ybfree_hree_concentrate'))
        .outputs(metaitem('beads.loaded_thulium_cation_exchange'))
        .fluidOutputs(fluid('xeno_tmfree_hree_concentrate'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()


ION_EXCHANGE.recipeBuilder()
        .inputs(metaitem('beads.rare_earth_cation_exchange'))
        .fluidInputs(fluid('xeno_tmfree_hree_concentrate'))
        .outputs(metaitem('beads.loaded_lutetium_cation_exchange'))
        .fluidOutputs(fluid('xeno_hree_waste'))
        .duration(20)
        .EUt(1)
        .buildAndRegister()
