name: Generate Modpack Changelog

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    paths:
      - 'mods/**'

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toml
          
      - name: Generate Changelog
        id: changelog
        run: |
          python .github/scripts/generate_changelog.py
          
      - name: Create changelog file
        run: |
          echo "${{ steps.changelog.outputs.changelog }}" > modpack-changelog.md
          
      - name: Upload changelog artifact
        uses: actions/upload-artifact@v3
        with:
          name: modpack-changelog
          path: modpack-changelog.md
          
      - name: Print changelog
        run: cat modpack-changelog.md
