name: Generate Modpack Changelog

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    paths:
      - 'mods/**'

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toml requests
      
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - run: npm install @iarna/toml
      - name: Get version
        id: get-version
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            try {
                const fs = require('fs')
                const toml = require('@iarna/toml')
                const tomlString = fs.readFileSync('./pack.toml')
                var apps = toml.parse(tomlString)
                return apps.version
            } catch(err) {
                core.error("Error while reading or parsing the TOML")
                core.setFailed(err)
            }
      
      - name: Run changelog script
        id: changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ORGANIZATION: "SymmetricDevs"
          VERSION: ${{ steps.get-version.outputs.result }}
        run: |
          chmod +x .github/scripts/generate_changelog.py
          python .github/scripts/generate_changelog.py
          
      - name: Upload changelog artifact
        uses: actions/upload-artifact@v4
        with:
          name: modpack-changelog
          path: modpack-changelog.md
          
      - name: Print changelog
        run: cat modpack-changelog.md
